#' Connect to the local offline database
#'
#' @param folder_path Character. The absolute or relative path to the directory
#'   containing the core Parquet files (`genotypes.parquet`, `variants.parquet`,
#'   `metadata.parquet`, `annotations.parquet`).
#' @param max_memory Character. Maximum RAM DuckDB is allowed to utilize.
#'   Defaults to '"8GB"'. Adjust based on system constraints.
#' @param quiet Logical. If \code{TRUE}, suppresses console messages. Defaults to \code{FALSE}.
#'
#' @return A DBI connection object (`con`) linked to the virtual database.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder, max_memory = "8GB")
#'
#' }
#'
#' @import DBI
#' @export
connect_local_db <- function(folder_path, max_memory = "8GB", quiet = FALSE) {

  expected_files <- c("genotypes.parquet", "variants.parquet",
                      "metadata.parquet", "annotations.parquet")

  for (f in expected_files) {
    full_path <- file.path(folder_path, f)
    if (!file.exists(full_path)) {
      stop(paste("Critical file missing:", f, "\nPlease check your folder path:", folder_path))
    }
  }

  con <- DBI::dbConnect(duckdb::duckdb())

  DBI::dbExecute(con, sprintf("PRAGMA memory_limit='%s'", max_memory))

  # Disable DuckDB progress bar to prevent console spam in Shiny
  DBI::dbExecute(con, "SET enable_progress_bar=false")

  # 4. Create virtual shortcuts (Views) using safe file paths
  DBI::dbExecute(con, sprintf("CREATE VIEW genotypes AS SELECT * FROM '%s'", file.path(folder_path, "genotypes.parquet")))
  DBI::dbExecute(con, sprintf("CREATE VIEW variants AS SELECT * FROM '%s'", file.path(folder_path, "variants.parquet")))
  DBI::dbExecute(con, sprintf("CREATE VIEW metadata AS SELECT * FROM '%s'", file.path(folder_path, "metadata.parquet")))
  DBI::dbExecute(con, sprintf("CREATE VIEW annotations AS SELECT * FROM '%s'", file.path(folder_path, "annotations.parquet")))

  if (!quiet) {
    message("Successfully connected to the local offline database! Virtual views mounted safely.")
  }

  return(con)
}




#' Disconnect the local database session
#'
#' @param con A valid DBI connection object generated by \code{connect_local_db()}.
#' @param quiet Logical. If \code{TRUE}, suppresses console messages. Defaults to \code{FALSE}.
#' @return None. Prints a message confirming the disconnection status.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder, max_memory = "8GB")
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#'
#' }
#'
#' @import DBI
#' @export
disconnect_local_db <- function(con, quiet = FALSE) {
  # Check if the connection exists and is currently open
  if (!missing(con) && inherits(con, "DBIConnection") && DBI::dbIsValid(con)) {
    DBI::dbDisconnect(con, shutdown = TRUE)
    if (!quiet) {
      message(
        "Successfully disconnected from the local database. Memory cleared."
      )
    }
  } else {
    if (!quiet) {
      message("The database connection is already closed or invalid.")
    }
  }
}




#' List all tables in the database (local)
#'
#' @param con A DBI connection object to the local database.
#' @return A character vector of table names in the database.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # List tables
#' list_sqlite_tables_result <- list_sqlite_tables(con)
#' print(list_sqlite_tables_result)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#'
#' }
#'
#' @export
#' @import DBI
list_sqlite_tables <- function(con) {
  # Ensure the connection object is valid
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Retrieve the list of tables from the database connection
  tables <- DBI::dbListTables(con)
  return(tables)
}




#' Get variant statistics from the database (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param include_annotations A logical value indicating whether to include
#'   statistics for the annotations table. Defaults to \code{TRUE}.
#'
#' @return A data frame of variant statistics grouped by chromosome.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#'
#' # Get variant statistics across all chromosomes
#' stats_df <- variant_stats(con, include_annotations = TRUE)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#'
#' }
#'
#' @import DBI
#' @export
variant_stats <- function(con, include_annotations = TRUE) {
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Extract base statistics from the variants table (counts, min/max pos, unique IDs)
  variant_stats <- DBI::dbGetQuery(
    con,
    "
    SELECT
      chrom,
      COUNT(*) AS n_variants,
      MIN(pos) AS min_pos,
      MAX(pos) AS max_pos,
      COUNT(DISTINCT variant_id) AS n_unique_ids
    FROM variants
    GROUP BY chrom
    ORDER BY chrom
  "
  )

  if (include_annotations) {
    # Query for the count of distinct annotated variants using an inner join
    annotation_counts <- DBI::dbGetQuery(
      con,
      "
      SELECT chrom, COUNT(DISTINCT v.variant_id) AS n_annotated
      FROM variants v
      JOIN annotations a ON v.variant_id = a.variant_id
      GROUP BY chrom
      ORDER BY chrom
    "
    )
    # Merge the annotation stats with the base stats
    variant_stats <- merge(
      variant_stats,
      annotation_counts,
      by = "chrom",
      all.x = TRUE
    )
    # Fill NA values with 0 for chromosomes lacking annotations
    variant_stats$n_annotated[is.na(variant_stats$n_annotated)] <- 0
  }

  return(variant_stats)
}




#' Get summary of database variant impacts by chromosome (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#'
#' @return A wide-format data frame where the first column is \code{chrom}, followed by
#'   pivoted columns for each impact type (e.g., \code{impact_HIGH}, \code{impact_MODERATE}),
#'   containing their respective mutation counts.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Generate the wide-format impact profile matrix
#' impact_matrix <- variant_impact_summary(con)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#'
#' }
#'
#' @import DBI
#' @export
variant_impact_summary <- function(con) {
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Dynamically pivot the data by counting occurrences of each impact type per chromosome
  query <- "
    PIVOT (
      SELECT v.chrom, a.impact
      FROM annotations a
      JOIN variants v ON a.variant_id = v.variant_id
    )
    ON impact
    USING COUNT(*)
    ORDER BY chrom
  "

  impact_wide <- DBI::dbGetQuery(con, query)
  if (nrow(impact_wide) == 0) {
    return(data.frame())
  }

  # Format column names for clarity (e.g. HIGH -> impact_HIGH)
  col_names <- colnames(impact_wide)
  colnames(impact_wide)[-1] <- paste0("impact_", col_names[-1])

  # Replace any NA with 0 for chromosomes that might be missing a specific impact type entirely
  impact_wide[is.na(impact_wide)] <- 0

  return(impact_wide)
}




#' Get table names and row counts from the database (local)
#'
#' Queries the active local database to instantly retrieve a list of all mounted
#' tables along with their respective total row counts.
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @return A data frame containing two columns: \code{table} (the table name)
#'   and \code{n_rows} (the total number of rows in that table).
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Get row counts for all mounted Parquet views
#' database_summary <- summarize_sqlite_tables(con)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
summarize_sqlite_tables <- function(con) {
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Fetch all available tables
  tables <- DBI::dbListTables(con)

  # Retrieve and store the total number of rows for each table
  counts <- sapply(tables, function(tbl) {
    query <- sprintf("SELECT COUNT(*) FROM %s", tbl)
    DBI::dbGetQuery(con, query)[[1]]
  })

  summary_df <- data.frame(
    table = tables,
    n_rows = counts,
    row.names = NULL
  )

  return(summary_df)
}


#' Get the genomic range of a candidate gene and its features using the Sobic ID from a GFF file (local)
#' @param gene_name A character value indicating the Sobic ID of candidate gene.
#' @param gff_path A character value specifying the path to gff3 file. GZ compressed
#' files and URL file paths are acceptable.
#' @returns A data frame containing the genomic coordinates (chromosome, start, end, strand)
#' of the gene, transcripts, 5'-UTR, CDS, and 3'-UTR.
#' @examples
#' \donttest{
#' # example code
#' library(panGenomeBreedr)
#' # Path to GFF3 file
#' gff_path <- "https://raw.githubusercontent.com/awkena/panGB/main/Sbicolor_730_v5.1.gene.gff3.gz"
#' gene_features <- gene_coord_gff(gene_name = "Sobic.005G213600",
#'                                 gff_path = gff_path)
#' head(gene_features)
#' }
#' @export
#' @importFrom R.utils isUrl isGzipped gunzip
gene_coord_gff <- function(gene_name, gff_path) {

  # Setup strictly unique temporary file paths to prevent namespace collisions
  temp_download <- tempfile(pattern = "dl_", fileext = ".gff3")
  temp_gff <- tempfile(pattern = "extracted_", fileext = ".gff3")

  # Ensure only these specific unique temp files are deleted on exit
  on.exit({
    if (file.exists(temp_download)) unlink(temp_download)
    if (file.exists(temp_gff)) unlink(temp_gff)
  }, add = TRUE)

  # Read GFF
  if (R.utils::isUrl(gff_path)) {
    utils::download.file(gff_path, destfile = temp_download, quiet = TRUE)

    if (R.utils::isGzipped(temp_download)) {
      R.utils::gunzip(temp_download, destname = temp_gff, overwrite = TRUE, remove = FALSE)
      gff <- utils::read.delim(temp_gff, comment.char = "#", header = FALSE, sep = "\t")
    } else {
      gff <- utils::read.delim(temp_download, comment.char = "#", header = FALSE, sep = "\t")
    }

  } else if (R.utils::isGzipped(gff_path)) {
    # Extract local compressed files temporarily without deleting the user's original file
    R.utils::gunzip(gff_path, destname = temp_gff, overwrite = TRUE, remove = FALSE)
    gff <- utils::read.delim(temp_gff, comment.char = "#", header = FALSE, sep = "\t")

  } else {
    gff <- utils::read.delim(gff_path, comment.char = "#", header = FALSE, sep = "\t")
  }

  # Assign standard column names based on the GFF format specifications
  colnames(gff) <- c("seqid", "source", "type", "start", "end", "score", "strand", "phase", "attributes")

  # 1. Identify the core gene
  gene_pattern <- paste0("(ID|Name)=", gene_name, "([;]|$)")
  gff_gene <- gff[gff$type == "gene" & grepl(gene_pattern, gff$attributes), ]

  if (nrow(gff_gene) == 0) stop("Gene not found in GFF.")
  if (nrow(gff_gene) > 1) {
    warning("Multiple gene matches found; using the first match.")
    gff_gene <- gff_gene[1, ]
  }

  # Extract the exact ID to reliably link child features
  gene_id <- sub(".*ID=([^;]+).*", "\\1", gff_gene$attributes)

  # 2. Extract transcripts (mRNAs)
  tx_pattern <- paste0("Parent=", gene_id, "([;]|$)")
  transcripts <- gff[gff$type %in% c("mRNA", "transcript") & grepl(tx_pattern, gff$attributes), ]

  # Initialize list to compile all target features
  results_list <- list()

  # Add the main gene block
  results_list[[1]] <- data.frame(
    ID = gene_id,
    Feature = "gene",
    Chromosome = gff_gene$seqid,
    Start = as.integer(gff_gene$start),
    End = as.integer(gff_gene$end),
    Strand = gff_gene$strand,
    stringsAsFactors = FALSE
  )

  # 3. Process each transcript and its sub-features
  if (nrow(transcripts) > 0) {
    for (i in seq_len(nrow(transcripts))) {
      tx <- transcripts[i, ]
      tx_id <- sub(".*ID=([^;]+).*", "\\1", tx$attributes)

      results_list[[length(results_list) + 1]] <- data.frame(
        ID = tx_id,
        Feature = tx$type,
        Chromosome = tx$seqid,
        Start = as.integer(tx$start),
        End = as.integer(tx$end),
        Strand = tx$strand,
        stringsAsFactors = FALSE
      )

      # Grab all children of this specific transcript (CDS, UTRs, etc.)
      child_pattern <- paste0("Parent=", tx_id, "([;]|$)")
      children <- gff[grepl(child_pattern, gff$attributes), ]

      if (nrow(children) > 0) {
        # Add the raw standard features directly
        results_list[[length(results_list) + 1]] <- data.frame(
          ID = tx_id,
          Feature = children$type,
          Chromosome = children$seqid,
          Start = as.integer(children$start),
          End = as.integer(children$end),
          Strand = children$strand,
          stringsAsFactors = FALSE
        )
      }
    }
  }

  # 4. Collapse and filter to user's desired features
  final_df <- do.call(rbind, results_list)

  target_features <- c("gene", "mRNA", "transcript", "five_prime_UTR", "CDS", "three_prime_UTR")
  final_df <- final_df[final_df$Feature %in% target_features, ]

  # Order logically by ID and Start position for clean downstream parsing
  final_df <- final_df[order(final_df$ID, final_df$Start), ]
  rownames(final_df) <- NULL

  return(final_df)
}


#' Plot the gene model using genomic coordinates (local)
#'
#' @description Visualizes the gene structure with adjusted component heights,
#' a cleaned legend, and a strand orientation arrow. Introns are implicitly
#' represented by the exposed transcript backbone.
#' @param gene_df A data frame containing the genomic coordinates, expected to
#' be the output from \code{gene_coord_gff}.
#' @returns A \code{ggplot} object representing the structural gene model.
#' @examples
#' \donttest{
#' library(panGenomeBreedr)
#' # Path to GFF3 file
#' gff_path <- "https://raw.githubusercontent.com/awkena/panGB/main/Sbicolor_730_v5.1.gene.gff3.gz"
#' gene_features <- gene_coord_gff(gene_name = "Sobic.005G213600",
#'                                 gff_path = gff_path)
#' # Plot gene model for Sobic.005G213600
#' plot_gene_model(gene_df = gene_features)
#' }
#' @export
#' @importFrom ggplot2 ggplot aes geom_rect geom_segment scale_fill_manual theme_minimal labs theme element_blank arrow
#' @importFrom grid unit
plot_gene_model <- function(gene_df) {

  Start <- End <- ymin <- ymax <- Feature <- x_start <- x_end <- NULL

  # 1. Assign geometric heights based on Feature types
  gene_df$ymin <- ifelse(gene_df$Feature == "CDS", -0.15,
                         ifelse(grepl("UTR", gene_df$Feature), -0.075, -0.01))

  gene_df$ymax <- ifelse(gene_df$Feature == "CDS", 0.15,
                         ifelse(grepl("UTR", gene_df$Feature), 0.075, 0.01))

  # 2. Sort the data frame to ensure the backbone is drawn first (bottom layer)
  gene_df <- gene_df[order(gene_df$ymax), ]

  # 3. Extract the backbone to map the strand direction arrow
  backbone <- gene_df[gene_df$Feature %in% c("gene", "mRNA", "transcript"), ]

  # Map arrow coordinates dynamically based on strand (+ points right, - points left)
  if (nrow(backbone) > 0) {
    backbone$x_start <- ifelse(backbone$Strand == "-", backbone$End, backbone$Start)
    backbone$x_end   <- ifelse(backbone$Strand == "-", backbone$Start, backbone$End)
  }

  # 4. Define the clean color palette
  type_colors <- c("five_prime_UTR"  = "#0E77F0", # Light blue
                   "CDS"             = "#FFA500", # orange
                   "three_prime_UTR" = "#009E73", # Green
                   "gene"            = "#999999", # Grey backbone
                   "mRNA"            = "#999999") # Grey fallback

  # 5. Plot the structure
  p <- ggplot2::ggplot() +

    # Draw rectangles for all features with a thin border
    ggplot2::geom_rect(data = gene_df,
                       ggplot2::aes(xmin = Start,
                                    xmax = End,
                                    ymin = ymin,
                                    ymax = ymax,
                                    fill = Feature,
                                    height = 0.01),
                       color = "black", linewidth = 0.3) +

    # Draw the orientation arrow running through the center of the backbone
    ggplot2::geom_segment(data = backbone,
                          ggplot2::aes(x = x_start,
                                       xend = x_end,
                                       y = 0,
                                       yend = 0),
                          arrow = ggplot2::arrow(length = grid::unit(0.1, "inches"),
                                                 type = "closed"),
                          color = "black", linewidth = 0.4) +

    # Map colors AND refine legend
    ggplot2::scale_fill_manual(values = type_colors, name = " ",
                               breaks = c("five_prime_UTR", "CDS", "three_prime_UTR"),
                               labels = c("5' UTR", "CDS", "3' UTR")) +

    ggplot2::theme_classic() +
    ggplot2::labs(x = "Genomic Position (bp)",
                  y = "") +

    # Clean up the y-axis
    ggplot2::theme(axis.line.y = ggplot2::element_blank(),
                   axis.text.y = ggplot2::element_blank(),
                   axis.line.x = ggplot2::element_blank(),
                   axis.ticks.y = ggplot2::element_blank(),
                   panel.grid.minor.y = ggplot2::element_blank(),
                   panel.grid.major.y = ggplot2::element_blank(),
                   panel.grid.minor.x = ggplot2::element_blank(),
                   panel.grid.major.x = ggplot2::element_line(color = "#E5E5E5",
                                                              linetype = "dashed"),
                   legend.position = "bottom")

  return(p)
}


#' Plot genomic variant hotspots (SNPs and INDELs) extracted from the database (local)
#'
#' @description Visualizes variant distributions across a genomic region.
#' Variants are mapped by position, with impact levels determining their
#' vertical placement (lollipop style) and variant types mapped to shapes.
#' @param var_df A data frame containing variant data. Required columns:
#' \code{variant_type} (character: "SNP", "INDEL"), \code{variant_id},
#' and \code{impact} (character: "MODIFIER", "LOW", "MODERATE", "HIGH").
#' @param chrom_col A character string specifying the chromosome column.
#' @param pos_col A character string specifying the variant position column.
#' @param start_pos A numeric integer for the region start. Default is the minimum
#' position in var_df.
#' @param end_pos A numeric integer for the region end. Default is the maximum
#' position in var_df.
#' @returns A \code{ggplot} object representing the variant hotspots.
#' @examples
#' \donttest{
#' library(panGenomeBreedr)
#' # Extract variants within the candidate gene: Sobic.005G213600
#' pg_gt_region <- pg_query_db(table_name = "variants",
#'                             chrom = "Chr05",
#'                             start = 75104537,
#'                             end = 75106403
#'                             )
#'
#' #' # Extract annotations for the candidate gene
#' pg_annota_region <- pg_query_db(table_name = "annotations",
#'                                 chrom = "Chr05",
#'                                 start = 75104537,
#'                                 end = 75106403,
#'                                 gene_name = "Sobic.005G213600"
#'                                 )
#'
#' var_df <- merge(pg_annota_region, pg_gt_region, by = "variant_id")
#'
#' plot_variant_hotspot(var_df)
#' }
#' @export
#' @importFrom ggplot2 ggplot aes geom_hline geom_segment geom_point scale_fill_manual scale_shape_manual scale_x_continuous scale_y_continuous theme_minimal labs theme element_blank element_text element_line guides guide_legend margin
#' @importFrom scales comma
#' @importFrom stats runif
plot_variant_hotspot <- function(var_df,
                                 chrom_col = "chrom.x",
                                 pos_col = "pos.x",
                                 start_pos = NULL,
                                 end_pos = NULL) {

  plot_y <- bae_y <- impact <- variant_type <- NULL

  # 1. Handle missing boundaries dynamically
  if (is.null(start_pos)) start_pos <- min(var_df[[pos_col]], na.rm = TRUE)
  if (is.null(end_pos)) end_pos <- max(var_df[[pos_col]], na.rm = TRUE)

  # 2. Assign base y-coordinates based on Impact levels to stratify them vertically
  var_df$base_y <- ifelse(var_df$impact == "HIGH", 4,
                          ifelse(var_df$impact == "MODERATE", 3,
                                 ifelse(var_df$impact == "LOW", 2, 1)))

  # Add deterministic jitter so the stem drop-lines align perfectly with the points
  set.seed(123)
  var_df$plot_y <- var_df$base_y + stats::runif(nrow(var_df), min = -0.3,
                                                max = 0.3)

  # 3. Calculate summary statistics for the dynamic caption (Fixed typo new_df -> var_df)
  total_vars <- length(unique(var_df$variant_id))
  n_snps <- length(unique(var_df$variant_id[var_df$variant_type == "SNP"]))
  n_indels <- length(unique(var_df$variant_id[var_df$variant_type == "INDEL"]))
  caption_text <- paste0("Total Unique Variants: ", total_vars,
                         " | SNPs: ", n_snps,
                         " | INDELS: ", n_indels)
  # Get chromosome number
  chr <- var_df[[chrom_col]][1]

  # 4. Define specific palettes mapped directly to the requested visual style
  impact_colors <- c("MODIFIER" = "#9A9DA9", # Greyish purple
                     "LOW"      = "#7198EC", # Blue
                     "MODERATE" = "#C98FD9", # Magenta/Purple
                     "HIGH"     = "#F70909") # Red

  type_shapes <- c("SNP"   = 21, # Filled circle (allows color borders)
                   "INDEL" = 24) # Filled triangle up

  # Ensure factor levels so legends are ordered from least to most impact
  var_df$impact <- factor(var_df$impact, levels = c("MODIFIER", "LOW", "MODERATE",
                                                    "HIGH"))

  # 5. Build the plot (Using .data[[]] for tidy evaluation of dynamic column strings)
  plt <- ggplot2::ggplot(var_df, ggplot2::aes(x = .data[[pos_col]])) +

    # Add the thick baseline representing the chromosome track
    ggplot2::geom_hline(yintercept = 0, color = "#C9D4E5", linewidth = 1.2) +

    # Add the stem drop-lines (must be drawn BEFORE points so they sit underneath)
    ggplot2::geom_segment(ggplot2::aes(x = .data[[pos_col]], xend = .data[[pos_col]],
                                       y = 0, yend = plot_y),
                          color = "#E0E0E0", linewidth = 0.3, alpha = 0.6) +

    # Add the variant points with fill mapped to impact, and shape mapped to type
    ggplot2::geom_point(ggplot2::aes(y = plot_y, fill = impact, shape = variant_type),
                        size = 3.5, color = "black", stroke = 0.4, alpha = 0.8) +

    # Map aesthetics explicitly
    ggplot2::scale_fill_manual(values = impact_colors, name = "Max Impact") +
    ggplot2::scale_shape_manual(values = type_shapes, name = "Variant Type") +

    # Apply labels and format x-axis limits with commas
    ggplot2::labs(title = caption_text,
                  subtitle = paste0(chr, ": ",
                                    scales::comma(start_pos), " - ",
                                    scales::comma(end_pos)),
                  x = "Genomic Position (bp)",
                  y = "") +

    # Use standard comma formatting for the x-axis scale
    ggplot2::scale_x_continuous(labels = scales::comma, limits = c(start_pos, end_pos)) +

    # Hardcode y-axis limits so the baseline rests cleanly near the bottom
    # Expanded up to 4.8 to accommodate the new HIGH impact jitter
    ggplot2::scale_y_continuous(limits = c(-0.2, 4.8)) +

    # Apply clean structural theme
    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(size = 14, face = "bold"),
      plot.subtitle = ggplot2::element_text(size = 10, color = "darkgrey"),

      # Position the caption text heavily to the left under the axis
      plot.caption = ggplot2::element_text(hjust = 0, size = 10, face = "bold",
                                           margin = ggplot2::margin(t = 15)),

      # Handle gridlines (vertical dashed only, mimicking standard genome browsers)
      panel.grid.major.x = ggplot2::element_line(color = "#E5E5E5", linetype = "dashed"),
      panel.grid.minor.x = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_blank(),
      panel.grid.minor.y = ggplot2::element_blank(),

      # Strip away standard y-axis visuals
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_blank(),

      # Clean up x-axis text
      axis.text.x = ggplot2::element_text(size = 10, color = "black"),

      # Position the legend
      legend.position = "right",
      legend.title = ggplot2::element_text(face = "bold", size = 9),
      legend.text = ggplot2::element_text(size = 8)
    ) +

    # Ensure legends correctly preview shapes (size and border)
    ggplot2::guides(fill = ggplot2::guide_legend(override.aes = list(shape = 21, size = 4)),
                    shape = ggplot2::guide_legend(override.aes = list(size = 4, fill = "darkgrey")))

  return(plt)
}


#' Generate a combined gene model and variant hotspot overlay plot (local)
#'
#' @description Generates a vertically stacked visualization aligning a structural
#' gene model with its corresponding regional variant hotspots.
#'
#' @details This wrapper function integrates genomic annotations and variant genotypes.
#' It natively queries the pangenome-scale variant relational database. Whether operating
#' in 'online' mode or 'local' mode, it leverages the underlying Parquet and DuckDB
#' architectures optimized for sorghum to efficiently retrieve variants
#' and their snpEff annotations before plotting.
#'
#' @param gene_name A character string indicating the Sobic ID of the candidate gene.
#' @param gff_path A character string specifying the path to the GFF3 file.
#' @param connect_db_mode A character string specifying the database connection mode:
#' either "online" or "local".
#' @param local_db_path A character string specifying the local folder path to the database
#' if running in "local" mode.
#' @param selected_variants An optional character vector of specific `variant_id`s to
#' highlight on the plot with vertical lines, enlarged points, and labels.
#' @param text_sz A numeric value for specifying text size for selected variants.
#'
#' @returns A \code{patchwork} object containing the combined, aligned plots.
#' @examples
#' \donttest{
#' library(panGenomeBreedr)
#' gff_path <- "https://raw.githubusercontent.com/awkena/panGB/main/Sbicolor_730_v5.1.gene.gff3.gz"
#' hotspot_overlay_plot(gene_name = "Sobic.005G213600",
#'                      gff_path = gff_path,
#'                      connect_db_mode = "online",
#'                      selected_variants = c("INDEL_Chr05_75104881", "INDEL_Chr05_75105587"))
#' }
#' @export
#' @importFrom ggplot2 geom_vline geom_point theme element_blank aes scale_y_continuous coord_cartesian
#' @importFrom ggrepel geom_text_repel
#' @importFrom patchwork plot_layout
hotspot_overlay_plot <- function(gene_name,
                                 gff_path,
                                 connect_db_mode = c("online", "local"),
                                 local_db_path = NULL,
                                 selected_variants = NULL,
                                 text_sz = 2.5) {

  # Ensure the connection mode is strictly validated
  connect_db_mode <- match.arg(connect_db_mode)

  # Fail fast: Check for missing local DB path before doing any expensive GFF or DB operations
  if (connect_db_mode == "local" && is.null(local_db_path)) {
    stop("Please provide the path to the local DB.")
  }

  # Get the gene model from the gff3 file
  gene_model <- gene_coord_gff(gene_name = gene_name, gff_path)

  # Plot the gene model
  gene_model_plot <- plot_gene_model(gene_df = gene_model)

  chr <- gene_model$Chromosome[1] # Get chromosome number

  # Get the start pos of the gene
  start_pos <- min(gene_model$Start[gene_model$Feature == "gene"], na.rm = TRUE)

  # Get the end pos of the gene
  end_pos <- max(gene_model$End[gene_model$Feature == "gene"], na.rm = TRUE)

  # Extract variants from DB depending on connection
  if (connect_db_mode == "online") {

    pg_gt_region <- pg_query_db(
      table_name = "variants",
      chrom = chr,
      start = start_pos,
      end = end_pos
    )

    # Extract annotations for the candidate gene
    pg_annota_region <- pg_query_db(
      table_name = "annotations",
      chrom = chr,
      start = start_pos,
      end = end_pos,
      gene_name = gene_name
    )

    var_df <- merge(pg_annota_region, pg_gt_region, by = "variant_id")

  } else {

    # Establish a virtual connection to the offline database engine
    con_demo <- connect_local_db(folder_path = local_db_path)

    # Extract variants within the genomic range of the gene
    gt_region <- query_db(con = con_demo,
                          table_name = "variants",
                          chrom = chr,
                          start = start_pos,
                          end = end_pos)

    #  Query snpEff annotations within a candidate locus gene region
    annota_region <- query_db(con = con_demo,
                              table_name = "annotations",
                              chrom = chr,
                              start = start_pos,
                              end = end_pos,
                              gene_name = gene_name)

    # Merge gt_region and annota_region data frames
    var_df <- merge(annota_region, gt_region, by = "variant_id")
  }

  # Generate the base hotspot plot
  hotspot_plot <- plot_variant_hotspot(var_df,
                                       start_pos = start_pos,
                                       end_pos = end_pos)

  # Remove the x-axis text and title from the top plot so it flows cleanly into the bottom plot
  hotspot_clean <- hotspot_plot +
    ggplot2::theme(axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank(),
                   axis.ticks.x = ggplot2::element_blank())

  # Annotate combined plot to show selected variants
  if (!is.null(selected_variants)) {

    # Filter the dataset for the selected variants
    sel_df <- var_df[var_df$variant_id %in% selected_variants, ]

    if (nrow(sel_df) > 0) {

      #1. Clean the variant labels for plotting (Remove redundant Chr info)
      # This dynamically replaces "_Chr05_" (or whatever 'chr' is) with a space
      sel_df$clean_label <- gsub(paste0("_", chr, "_"), " ", sel_df$variant_id,
                                 ignore.case = TRUE)

      # Replicate the deterministic y-axis mapping used in plot_variant_hotspot
      # so the overlay coordinates perfectly match the underlying plot
      sel_df$base_y <- ifelse(sel_df$impact == "HIGH", 4,
                              ifelse(sel_df$impact == "MODERATE", 3,
                                     ifelse(sel_df$impact == "LOW", 2, 1)))

      # We must replicate the jitter on the FULL df first to match the original seed alignment
      set.seed(123)
      var_df$base_y <- ifelse(var_df$impact == "HIGH", 4,
                              ifelse(var_df$impact == "MODERATE", 3,
                                     ifelse(var_df$impact == "LOW", 2, 1)))
      var_df$plot_y <- var_df$base_y + stats::runif(nrow(var_df), min = -0.3, max = 0.3)

      # Now extract the exactly matched y-coordinates
      sel_df$plot_y <- var_df$plot_y[match(sel_df$variant_id, var_df$variant_id)]


      # 1. Add vertical dotted lines bridging both plots
      hotspot_clean <- hotspot_clean +
        ggplot2::geom_vline(xintercept = sel_df$pos.x, linetype = "dotted", color = "black", alpha = 0.6)

      gene_model_plot <- gene_model_plot +
        ggplot2::geom_vline(xintercept = sel_df$pos.x, linetype = "dotted", color = "black", alpha = 0.6)

      # 3. Expand the y-axis to prevent the nudged coordinates and tall vertical text from being dropped
      suppressMessages({
        hotspot_clean <- hotspot_clean +
          ggplot2::scale_y_continuous(limits = c(-0.2, 7.5)) +
          ggplot2::coord_cartesian(clip = "off")
      })

      # 2. Add enlarged points and names to the hotspot plot
      hotspot_clean <- hotspot_clean +
        ggplot2::geom_point(data = sel_df,
                            ggplot2::aes(x = pos.x, y = plot_y),
                            size = 5, color = "black", shape = 21, stroke = 1) +
        ggrepel::geom_text_repel(data = sel_df,
                                 ggplot2::aes(x = pos.x, y = plot_y, label = clean_label),
                                 size = text_sz,
                                 fontface = "bold",
                                 angle = 90,           # Rotate labels vertically
                                 hjust = 0,            # Anchor text cleanly at the bottom
                                 vjust = 0.5,          # Center align the line to the text base
                                 nudge_y = 0.8,        # Push text upward to clear the plotting space
                                 direction = "x",      # Force ggrepel to only spread them sideways if they overlap
                                 max.overlaps = Inf)   # Force all requested labels to draw
    }
  }

  # Stack them together using patchwork
  # 'heights = c(4, 1)' makes the variant plot 4 times taller than the gene model track
  # 'axes = "collect"' ensures they perfectly align along the Genomic Position
  final_overlay <- hotspot_clean / gene_model_plot +
    patchwork::plot_layout(heights = c(4, 1), axes = "collect")

  # View the final combined plot
  return(final_overlay)
}



#' Get table schema details (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param table_name A character value specifying the name of the table to inspect.
#'   Must be one of \code{"variants"}, \code{"annotations"}, or \code{"genotypes"}.
#'
#' @return A data frame containing the schema details of the target table, including
#'   column names and data types.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Inspect the schema layout of the variants table
#' column_schema <- list_table_columns(con, table_name = "variants")
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
list_table_columns <- function(
  con,
  table_name = c("variants", "annotations", "genotypes")
) {
  table_name <- match.arg(table_name)

  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  query <- sprintf("DESCRIBE %s", table_name)
  info <- DBI::dbGetQuery(con, query)

  return(info)
}




#' Query database tables by genomic coordinates (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param table_name A character value specifying the target view to query.
#'   Must be one of \code{"variants"}, \code{"annotations"}, or \code{"genotypes"}.
#' @param chrom A character value specifying the target chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Optional start coordinate for the target window region.
#' @param end Integer. Optional end coordinate for the target window region.
#' @param gene_name A character value indicating the specific Sobic gene model ID.
#'   Utilized explicitly when subsetting the \code{"annotations"} layout.
#'
#' @return A data frame containing the targeted genomic records. For the \code{"genotypes"}
#'   table, it returns individual samples unpacked directly into intuitive wide columns.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Extract functional functional annotations inside a candidate locus region
#' annota_region <- query_db(con = con, chrom = "Chr05", start = 75104537,
#'                           end = 75106403, table_name = "annotations",
#'                           gene_name = "Sobic.005G213600")
#'
#' # Extract matrix genotypes within the exact same coordinates window
#' gt_region <- query_db(con = con, chrom = "Chr05", start = 75104537,
#'                       end = 75106403, table_name = "genotypes")
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#'
#' }
#'
#' @import DBI
#' @export
query_db <- function(
  con,
  table_name = c("variants", "annotations", "genotypes"),
  chrom,
  start = NULL,
  end = NULL,
  gene_name = NULL
) {
  table_name <- match.arg(table_name)

  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Check if table exists
  all_tables <- DBI::dbListTables(con)
  if (!(table_name %in% all_tables)) {
    stop(sprintf("Table '%s' does not exist in the database.", table_name))
  }

  # ---  Annotations ---
  if (table_name == "annotations") {
    # Create an inner join across the annotations and variants table to filter by chrom and pos
    sql <- "
      SELECT a.*, v.chrom, v.pos
      FROM annotations a
      JOIN variants v ON a.variant_id = v.variant_id
      WHERE v.chrom = ?"

    params <- list(chrom)

    if (!is.null(start) && !is.null(end)) {
      sql <- paste(sql, "AND v.pos BETWEEN ? AND ?")
      params <- append(params, list(start, end))
    }

    # Filter by gene_name directly in SQL
    if (!is.null(gene_name)) {
      sql <- paste(sql, "AND a.gene_name = ?")
      params <- append(params, list(gene_name))
    }

    sql <- paste(sql, "ORDER BY v.pos")
    result <- DBI::dbGetQuery(con, sql, params = params)

    return(result)
  }

  # --- Genotypes ---
  if (table_name == "genotypes") {
    # Dynamically pull columns to safely support both wide and array-packed 'calls' storage formats
    gt_cols <- DBI::dbListFields(con, "genotypes")
    gt_data_cols <- setdiff(gt_cols, c("variant_id", "chrom", "pos"))
    gt_cols_sql <- paste0("g.", gt_data_cols, collapse = ", ")

    sql <- sprintf(
      "
      SELECT g.variant_id, g.chrom, g.pos, v.variant_type, v.ref, v.alt, %s
      FROM genotypes g
      JOIN variants v ON g.variant_id = v.variant_id
      WHERE g.chrom = ?",
      gt_cols_sql
    )

    params <- list(chrom)

    if (!is.null(start) && !is.null(end)) {
      sql <- paste(sql, "AND g.pos BETWEEN ? AND ?")
      params <- append(params, list(start, end))
    }

    sql <- paste(sql, "ORDER BY g.pos")
    result <- DBI::dbGetQuery(con, sql, params = params)

    if (nrow(result) == 0) {
      return(result)
    }

    # Unpack the array
    if ("calls" %in% gt_data_cols && length(gt_data_cols) == 1) {

      parsed_list <- result$calls

      sample_names <- NULL

      # Retrieve sample names from metadata
      if ("metadata" %in% all_tables) {
        sample_metadata <- DBI::dbGetQuery(
          con,
          "SELECT lib FROM metadata ORDER BY array_index ASC"
        )

        # Safely extract the first column (assuming it holds the library/sample name)
        if (ncol(sample_metadata) > 0) {
          sample_names <- sample_metadata[[1]]
        }
      }

      if (
        is.null(sample_names) ||
          length(sample_names) != length(parsed_list[[1]])
      ) {
        sample_names <- paste0("Sample_", seq_len(length(parsed_list[[1]])))
      }

      # Reconstruct the matrix to hold all sample calls instantly
      gt_matrix <- do.call(rbind, parsed_list)
      colnames(gt_matrix) <- sample_names

      # Combine the metadata columns with the expanded genotype matrix
      info_cols <- result[, setdiff(names(result), "calls"), drop = FALSE]
      result <- cbind(
        info_cols,
        as.data.frame(gt_matrix, stringsAsFactors = FALSE)
      )
    }

    # Append major/minor allele and freq
    result <- append_locus_allele_metrics(region_matrix = result)
    return(result)

  }

  # --- Variants ---
  # Directly pull and optionally filter variant metadata
  sql <- "
    SELECT * FROM variants v
    WHERE v.chrom = ?"

  params <- list(chrom)

  if (!is.null(start) && !is.null(end)) {
    sql <- paste(sql, "AND v.pos BETWEEN ? AND ?")
    params <- append(params, list(start, end))
  }

  sql <- paste(sql, "ORDER BY v.pos")
  result <- DBI::dbGetQuery(con, sql, params = params)

  return(result)
}




#' Extract variants based on functional mutation impact (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param impact_level A character vector specifying the variant impact types to retain.
#'   Allowed classifications are \code{"HIGH"}, \code{"MODERATE"}, \code{"LOW"}, and \code{"MODIFIER"}.
#' @param chrom A character value specifying the chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Start coordinate for the genomic region.
#' @param end Integer. End coordinate for the genomic region.
#'
#' @return A data frame of variants showing their functional impact details
#'   and positional coordinates.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Extract high-impact variant lines inside a targeted coordinates locus window
#' high_impact_vars <- query_by_impact(con = con,
#'                                     impact_level = "HIGH",
#'                                     chrom = "Chr05",
#'                                     start = 75104537,
#'                                     end = 75106403)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
query_by_impact <- function(
  con,
  impact_level = c("HIGH", "MODERATE", "LOW", "MODIFIER"),
  chrom = NULL,
  start = NULL,
  end = NULL
) {
  # Validate the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Intersect with allowed options to sanitize the impact levels provided by the user
  allowed <- c("HIGH", "MODERATE", "LOW", "MODIFIER")
  impact_level <- intersect(toupper(impact_level), allowed)

  if (length(impact_level) == 0) {
    stop("No valid impact levels provided.")
  }

  # Dynamically build standard SQL IN placeholders
  placeholders <- paste(rep("?", length(impact_level)), collapse = ", ")

  # Join annotations and variants to retrieve requested variants safely via parameterization
  sql <- sprintf(
    "
    SELECT v.*, a.allele, a.annotation, a.impact, a.gene_name,
           a.gene_id, a.feature_type, a.feature_id, a.transcript_biotype,
           a.rank, a.HGVS_c, a.HGVS_p
    FROM variants v
    JOIN annotations a ON v.variant_id = a.variant_id
    WHERE a.impact IN (%s)",
    placeholders
  )
  params <- as.list(impact_level)

  if (!is.null(chrom)) {
    sql <- paste(sql, "AND v.chrom = ?")
    params <- append(params, list(chrom))

    if (!is.null(start) && !is.null(end)) {
      sql <- paste(sql, "AND v.pos BETWEEN ? AND ?")
      params <- append(params, list(start, end))
    }
  }

  sql <- paste(sql, "ORDER BY v.chrom, v.pos")
  result <- DBI::dbGetQuery(con, sql, params = params)

  return(result)
}




#' Compute allele frequencies for a genotype matrix (local)
#'
#' @param gt A matrix or data frame containing variants (rows) across samples (columns),
#'   including required variant identification and optional genomic coordinate metadata columns.
#' @param variant_id_col Character. The column name in \code{gt} matching unique variant identifiers.
#'   Defaults to \code{"variant_id"}.
#' @param chrom_col Character. Optional column name in \code{gt} matching chromosome names.
#'   Defaults to \code{NULL}.
#' @param pos_col Character. Optional column name in \code{gt} matching genomic positions.
#'   Defaults to \code{NULL}.
#'
#' @return A data frame containing unique variant identifiers, optional coordinate tracking columns,
#'   calculated reference allele frequencies (\code{ref_af}), and alternate allele frequencies (\code{alt_af}).
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Pull wide genotype records for a locus window range
#' gt_region <- query_db(con = con, chrom = "Chr05", start = 75104537,
#'                       end = 75106403, table_name = "genotypes")
#'
#' # Compute allele frequencies across all samples in the dataset
#' af_metrics <- calc_af(gt_region, variant_id_col = "variant_id",
#'                       chrom_col = "chrom", pos_col = "pos")
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @export
calc_af <- function(gt,
                    variant_id_col = 'variant_id',
                    chrom_col = NULL,
                    pos_col = NULL){

  # if(!is.null(chrom)) chrom <- chrom
  # if(!is.null(pos)) pos <- pos

  # Exclude non-genotype mapping/reference columns
  sample_cols <- setdiff(colnames(gt), c(variant_id_col, chrom_col, pos_col))
  gt_matrix <- gt[, sample_cols, drop = FALSE]

  # Function to convert GT string to ALT dosage (0, 1, 2)
  parse_gt <- function(gt) {
    if (is.na(gt)) return(NA)
    if (gt %in% c("0|0", "0/0")) return(0)
    if (gt %in% c("0|1", "1|0", "0/1", "1/0")) return(1)
    if (gt %in% c("1|1", "1/1")) return(2)
    return(NA)  # For unexpected/missing codes
  }

  # Apply conversion function across all sample calls
  dosage_mat <- as.data.frame(apply(gt_matrix, c(1, 2), parse_gt),
                              stringsAsFactors = FALSE)

  # Calculate the alternate allele frequency based on dosages (sum of alt alleles / 2n samples)
  if(nrow(dosage_mat) > 1){
    alt_af <- rowMeans(sapply(dosage_mat, as.numeric), na.rm = TRUE) / 2
  } else{
    # Handle isolated single variant cases cleanly without rowMeans failing
    alt_af <- mean(sapply(dosage_mat, as.numeric), na.rm = TRUE) / 2
  }

  # Format the output data frame with IDs and calculated frequencies
  if(is.null(chrom_col) && is.null(pos_col) ) {

    result <- data.frame(variant_id = gt[, variant_id_col], ref_af = 1 - alt_af,
                         alt_af = alt_af)

  } else {

    result <- data.frame(gt[, c(variant_id_col, chrom_col, pos_col)],
                         ref_af = 1 - alt_af,
                         alt_af = alt_af)

  }

  return(result)

}




#' Filter genotypes by allele frequency (Local)
#'
#' @param gt A data frame containing genotype calls queried from the genotypes table.
#' @param variant_id_col Character. The column name in \code{gt} matching unique variant identifiers.
#'   Defaults to \code{"variant_id"}.
#' @param chrom_col Character. The column name in \code{gt} matching chromosome names.
#'   Defaults to \code{"chrom"}.
#' @param pos_col Character. The column name in \code{gt} matching genomic positions.
#'   Defaults to \code{"pos"}.
#' @param min_af Numeric. Minimum alternate allele frequency threshold for filtering.
#'   Must fall between 0 and 1. Defaults to \code{0}.
#' @param max_af Numeric. Maximum alternate allele frequency threshold for filtering.
#'   Must fall between 0 and 1. Defaults to \code{1}.
#'
#' @return A data frame of variants passing the frequency thresholds, tracking their coordinates,
#'   calculated reference allele frequencies (\code{ref_af}), and alternate allele frequencies (\code{alt_af}).
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Query genotypes
#' gt_region <- query_db(con = con, chrom = "Chr05", start = 75104537,
#'                       end = 75106403, table_name = "genotypes")
#'
#' # Filter out rare variants or monomorphic lines by restricting the alternate allele frequency window
#' filtered_vars <- filter_by_af(gt_region, variant_id_col = "variant_id",
#'                               chrom_col = "chrom", pos_col = "pos",
#'                               min_af = 0.05, max_af = 0.95)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @export
filter_by_af <- function(gt,
                         variant_id_col = 'variant_id',
                         chrom_col = 'chrom',
                         pos_col = 'pos',
                         min_af = 0,
                         max_af = 1) {

  if (nrow(gt) == 0) {
    stop("No variant found in the genotype matrix.")
  }

  result <- calc_af(gt,
                    variant_id_col = variant_id_col,
                    chrom_col = chrom_col,
                    pos_col = pos_col)

  # Filter by allele frequency
  result <- result[result$alt_af >= min_af & result$alt_af <= max_af, ]

  return(result)
}





#' Query variants by allele frequency (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param min_af Numeric. Minimum alternate allele frequency threshold for filtering.
#'   Must fall between 0 and 1. Defaults to \code{0}.
#' @param max_af Numeric. Maximum alternate allele frequency threshold for filtering.
#'   Must fall between 0 and 1. Defaults to \code{1}.
#' @param chrom A character value specifying the target chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Start coordinate for the target window region.
#' @param end Integer. End coordinate for the target window region.
#'
#' @return A data frame of variants passing the frequency thresholds within the defined region,
#'   tracking their coordinates, calculated reference allele frequencies (\code{ref_af}),
#'   and alternate allele frequencies (\code{alt_af}).
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Query a specific locus window and filter for common variants (MAF >= 5%)
#' query_by_af_result <- query_by_af(con = con,
#'                                 min_af = 0.05,
#'                                 max_af = 0.95,
#'                                 chrom = "Chr05",
#'                                 start = 75104537,
#'                                 end = 75106403)
#' print(query_by_af_result)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @export
query_by_af <- function(
  con,
  min_af = 0,
  max_af = 1,
  chrom = NULL,
  start = NULL,
  end = NULL
) {
  if (is.null(chrom)) {
    stop("Chromosome must be specified.")
  }

  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # First, query all genotypes in the region
  gt <- query_db(
    con = con,
    table_name = "genotypes",
    chrom = chrom,
    start = start,
    end = end
  )

  if (nrow(gt) == 0) {
    message("No genotype data found for specified region.")
    return(data.frame())
  }

  # Second, calculate the frequencies to allow for subsetting
  result <- calc_af(
    gt,
    variant_id_col = 'variant_id',
    chrom_col = 'chrom',
    pos_col = 'pos'
  )

  # Filter by the minimum and maximum allele frequencies
  result <- result[result$alt_af >= min_af & result$alt_af <= max_af, ]

  return(result)
}





#' Query genotypes table for specific variant IDs (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param variant_ids A character vector of unique variant identifiers to look up (e.g., \code{c("SNP_Chr05_75104557")}).
#' @param variant_id_col A character value specifying the primary key column name for variant IDs.
#'   Defaults to \code{"variant_id"}.
#' @param variants_table A character value specifying the name of the variants reference table view.
#'   Defaults to \code{"variants"}.
#' @param genotypes_table A character value specifying the name of the genotype call data table view.
#'   Defaults to \code{"genotypes"}.
#' @param meta_data A character vector of metadata columns to return alongside
#'   the genotype matrix. This can include any field from the `variants` table
#'   (e.g., `"chrom"`, `"pos"`, `"ref"`, `"alt"`, `"variant_type"`) as well as
#'   dynamically calculated metrics: `"major_allele"`, `"minor_allele"`,
#'   `"major_allele_freq"`, and `"minor_allele_freq"`. If `NULL` (default),
#'   all available database fields and all calculated metrics are returned.
#'
#' @return A data frame containing mapped metadata tracking columns alongside individual sample genotype
#'   calls formatted in a structured variants-by-samples matrix.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Extract all sample genotypes for an explicit list of target marker strings
#' target_markers <- c("INDEL_Chr05_75104541", "SNP_Chr05_75104557")
#'
#' query_genotypes_result <- query_genotypes(con = con,
#'                                  variant_ids = target_markers,
#'                                  meta_data = c('chrom','minor_allele_freq'))
#' print(query_genotypes_result)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
query_genotypes <- function(
  con,
  variant_ids,
  variant_id_col = "variant_id",
  variants_table = 'variants',
  genotypes_table = 'genotypes',
  meta_data = NULL
) {


  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Predefine user request
  user_requested_cols <- meta_data
  wants_all_data <- is.null(meta_data)

  # Prevent execution if no variant IDs are provided
  if (length(variant_ids) == 0) {
    warning("The 'variant_ids' vector is empty. No query was executed.")
    return(data.frame())
  }

  # Check if required tables exist in DB
  all_tables <- DBI::dbListTables(con)
  if (!(variants_table %in% all_tables) || !(genotypes_table %in% all_tables)) {
    stop(
      "The specified variants or genotypes table does not exist in the database."
    )
  }


  # Columns present in `append_locus_allele_metrics`
  calculated_metric_cols <- c("major_allele", "minor_allele", "major_allele_freq", "minor_allele_freq")

  # Get all available fields from the variants table in the DB
  db_variant_fields <- DBI::dbListFields(con, variants_table)

  # Determine which columns to fetch from the database
  if (wants_all_data) {
    cols_to_fetch <- db_variant_fields
  } else {
    user_db_cols <- intersect(user_requested_cols, db_variant_fields)

    required_for_calc <- c("ref", "alt")

    cols_to_fetch <- unique(c(variant_id_col, user_db_cols, required_for_calc))
  }

  # Construct safe comma-separated column names for metadata and genotypes
  meta_cols_sql <- paste0("v.", cols_to_fetch, collapse = ", ")

  gt_cols <- DBI::dbListFields(con, genotypes_table)
  gt_data_cols <- setdiff(gt_cols, c(variant_id_col, "chrom", "pos"))
  gt_cols_sql <- paste0("g.", gt_data_cols, collapse = ", ")

  placeholders <- paste(rep("?", length(variant_ids)), collapse = ", ")
  params <- as.list(variant_ids)

  sql <- sprintf(
    "
    SELECT %s, %s
    FROM %s v
    JOIN %s g
      ON v.%s = g.%s
      AND v.chrom = g.chrom
      AND v.pos = g.pos
    WHERE v.%s IN (%s)
    ORDER BY v.chrom, v.pos",
    meta_cols_sql,
    gt_cols_sql,
    variants_table,
    genotypes_table,
    variant_id_col,
    variant_id_col,
    variant_id_col,
    placeholders
  )

  res <- DBI::dbGetQuery(con, sql, params = params)

  if (nrow(res) == 0) {
    warning("No data found for the provided variant IDs.")
    return(data.frame())
  }

  if ("pos" %in% colnames(res)) {
    res$pos <- as.integer(res$pos)
  }


  # Unpack genotype calls column
  parsed_list <- res$calls

  sample_names <- NULL
  if ("metadata" %in% all_tables) {
    sample_metadata <- DBI::dbGetQuery(
      con,
      "SELECT lib FROM metadata ORDER BY array_index ASC"
    )
    if (ncol(sample_metadata) > 0) {
      sample_names <- sample_metadata[[1]]
    }
  }

  # Fallback if sample names can't be retrieved or don't match
  if (is.null(sample_names) || length(parsed_list) == 0 || length(sample_names) != length(parsed_list[[1]])) {
    sample_names <- paste0("Sample_", seq_len(length(parsed_list[[1]])))
  }

  gt_matrix <- do.call(rbind, parsed_list)
  colnames(gt_matrix) <- sample_names

  info_cols <- res[, setdiff(names(res), "calls"), drop = FALSE]
  unpacked_res <- cbind(info_cols, as.data.frame(gt_matrix, stringsAsFactors = FALSE))

  # computing metrics to ensure the are available when needed
  result_with_metrics <- append_locus_allele_metrics(
    region_matrix = unpacked_res,
    meta_data = cols_to_fetch
  )

  # Result output
  if (wants_all_data) {
    return(result_with_metrics)
  } else {
 all_meta_cols <- c(db_variant_fields, calculated_metric_cols)

    sample_cols <- setdiff(colnames(result_with_metrics), all_meta_cols)
    final_cols_to_return <- c(variant_id_col, user_requested_cols, sample_cols)
    final_cols_to_return <- intersect(final_cols_to_return, colnames(result_with_metrics))

    return(result_with_metrics[, final_cols_to_return, drop = FALSE])
  }
}




#' Count the distribution of variant types in the database (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param variants_table Character. The name of the table containing variant
#'   metadata. Defaults to "variants".
#'
#' @return A data frame containing two columns: \code{variant_type} (the structural
#'   classification group name) and \code{n} (the total count of variants in that group).
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Get the breakdown counts of SNPs vs INDELs
#' count_variant_types_result <- count_variant_types(con)
#' print(count_variant_types_result)
#'
#' # Disconnnect at the end of the session.
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
count_variant_types <- function(con, variants_table = "variants") {

  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  cols <- DBI::dbListFields(con, variants_table)
  if (!"variant_type" %in% cols) {
    stop(sprintf(
      "The '%s' table does not have a 'variant_type' column.",
      variants_table
    ))
  }

  query <- sprintf(
    "SELECT variant_type, COUNT(*) AS n FROM %s GROUP BY variant_type ORDER BY variant_type",
    variants_table
  )

  result <- DBI::dbGetQuery(con, query)

  return(result)
}




#' Get summarized functional annotations, impacts and variant types for a genomic region (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param chrom A character value specifying the target chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Start coordinate for the target window region.
#' @param end Integer. End coordinate for the target window region.
#' @param annotations_table A character value specifying the name of the annotations reference table.
#'   Defaults to \code{"annotations"}.
#' @param variants_table A character value specifying the name of the variants reference table.
#'   Defaults to \code{"variants"}.
#'
#' @return A list object containing three summarized summary data frames:
#' \itemize{
#'   \item \code{annotation_summary}: Counts of distinct functional mutations grouped by type.
#'   \item \code{impact_summary}: Counts of predicted functional impacts grouped by type.
#'   \item \code{variant_type_totals}: Entire marker breakdown counts across the defined coordinate window.
#' }
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Extract functional distribution summaries across a specific gene locus window
#' query_ann_summary_result <- query_ann_summary(con = con,
#'                                         chrom = "Chr05",
#'                                         start = 75104537,
#'                                         end = 75106403)
#' print(query_ann_summary_result)
#'
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @export
query_ann_summary <- function(
  con,
  chrom,
  start,
  end,
  annotations_table = "annotations",
  variants_table = "variants"
) {
  # Check if the database connection is valid
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Validate required fields exist safely to ensure query compatibility
  ann_fields <- DBI::dbListFields(con, annotations_table)
  var_fields <- DBI::dbListFields(con, variants_table)

  required_ann <- c("variant_id", "annotation", "impact")
  required_var <- c("variant_id", "chrom", "pos", "variant_type")

  if (!all(required_ann %in% ann_fields)) {
    stop(
      "Annotations table must contain: ",
      paste(required_ann, collapse = ", ")
    )
  }
  if (!all(required_var %in% var_fields)) {
    stop("Variants table must contain: ", paste(required_var, collapse = ", "))
  }

  params <- list(chrom, start, end)

  # Aggregate total variants by their types
  sql_totals <- sprintf(
    "
    SELECT variant_type, COUNT(*) AS total_variants
    FROM %s
    WHERE chrom = ? AND pos BETWEEN ? AND ?
    GROUP BY variant_type",
    variants_table
  )

  variant_type_totals <- DBI::dbGetQuery(con, sql_totals, params = params)

  # Aggregate functional annotations counts categorized by variant type
  sql_ann <- sprintf(
    "
    SELECT a.annotation, v.variant_type, COUNT(*) AS count
    FROM %s a
    JOIN %s v ON a.variant_id = v.variant_id
    WHERE v.chrom = ? AND v.pos BETWEEN ? AND ?
    GROUP BY a.annotation, v.variant_type
    ORDER BY count DESC",
    annotations_table,
    variants_table
  )

  annotation_summary <- DBI::dbGetQuery(con, sql_ann, params = params)

  # Aggregate predicted functional impact counts categorized by variant type
  sql_impact <- sprintf(
    "
    SELECT a.impact, v.variant_type, COUNT(*) AS count
    FROM %s a
    JOIN %s v ON a.variant_id = v.variant_id
    WHERE v.chrom = ? AND v.pos BETWEEN ? AND ?
    GROUP BY a.impact, v.variant_type
    ORDER BY count DESC",
    annotations_table,
    variants_table
  )

  impact_summary <- DBI::dbGetQuery(con, sql_impact, params = params)

  if (nrow(variant_type_totals) == 0) {
    warning("No variants found in the specified region.")
    return(list(
      annotation_summary = data.frame(),
      impact_summary = data.frame(),
      variant_type_totals = data.frame()
    ))
  }

  return(list(
    annotation_summary = annotation_summary,
    impact_summary = impact_summary,
    variant_type_totals = variant_type_totals
  ))
}




#' Get samples metadata from the database (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param query_col Character. Optional metadata column name to filter by (e.g., \code{"countryorigin"}).
#'   If \code{NULL}, all database metadata records are returned.
#' @param query_value Character or Numeric. The explicit attribute value to match within \code{query_col}.
#'
#' @return A data frame containing the sample metadata records, strictly sorted by their
#'   \code{array_index} field to ensure perfect structural alignment with downstream genotype matrix.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Fetch metadata for all sorghum accessions originating from Ethiopia
#' get_sample_metadata_result <- get_sample_metadata(con = con,
#'                                    query_col = "countryorigin",
#'                                    query_value = "Ethiopia")
#'
#' print(get_sample_metadata_result)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#'
#' }
#'
#' @import DBI
#' @export
get_sample_metadata <- function(
  con,
  query_col = NULL,
  query_value = NULL
) {
  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  if (!("metadata" %in% DBI::dbListTables(con))) {
    stop("Table 'metadata' not found in the database.")
  }

  # Prevent SQL injection by validating query column against database schema
  if (!is.null(query_col)) {
    available_cols <- DBI::dbListFields(con, "metadata")
    if (!query_col %in% available_cols) {
      stop(sprintf("Column '%s' not found in the metadata table.", query_col))
    }
  }

  sql <- "SELECT * FROM metadata"
  params <- list()

  if (!is.null(query_col) && !is.null(query_value)) {
    sql <- paste0(sql, " WHERE ", query_col, " = ?")
    params <- list(query_value)
  }

  # Enforce sort by array_index to maintain correct alignment mapping with genotypes matrices
  sql <- paste0(sql, " ORDER BY array_index ASC")

  if (length(params) > 0) {
    result <- DBI::dbGetQuery(con, sql, params = params)
  } else {
    result <- DBI::dbGetQuery(con, sql)
  }

  return(result)
}




#' Filter genotypes by multiple sample metadata criteria (local)
#'
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param genotype_matrix A data frame or matrix where rows are variants and
#'   columns include variant metadata followed by sample genotypes.
#' @param genotype_start_col An integer specifying the column index where sample
#'   genotype calls begins.
#' @param filters A named list of metadata criteria to filter samples by.
#'   Names must match metadata schema columns, and values are the allowed entries.
#'   Example: \code{list(population = "Gates", countryorigin = c("Ethiopia", "Ghana", "Togo"))}
#'
#' @return A data frame containing the filtered genotype matrix with recalculated
#'   allele metrics for the sub-population. Returns an empty data frame if no
#'   samples match all combined criteria.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Define filtering criteria
#' my_filters <- list(
#'   population = "Gates",
#'   countryorigin = c("Ethiopia", "Ghana", "Togo")
#' )
#'
#' # Extract the full genotype matrix first for the genomic region
#' query_db_result <- query_db(
#'   con = con,
#'   table_name = "genotypes",
#'   chrom = "Chr05",
#'   start = 75104537,
#'   end = 75106403
#' )
#'
#' # Get filtered genotypes matrix
#' query_geno_by_meta_result <- query_geno_by_meta(
#'   con = con,
#'   genotype_matrix = query_db_result,
#'   genotype_start_col = 11,
#'   filters = my_filters
#' )
#' print(query_geno_by_meta_result)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @export
query_geno_by_meta <- function(
  con,
  genotype_matrix,
  genotype_start_col,
  filters
) {
  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Validate matrix inputs
  if (!is.data.frame(genotype_matrix) && !is.matrix(genotype_matrix)) {
    stop("`genotype_matrix` must be a data frame or matrix.", call. = FALSE)
  }
  if (nrow(genotype_matrix) == 0) {
    warning("Input `genotype_matrix` is empty.", call. = FALSE)
    return(data.frame())
  }
  if (!is.numeric(genotype_start_col) || genotype_start_col <= 1) {
    stop(
      "`genotype_start_col` must be a numeric value greater than 1.",
      call. = FALSE
    )
  }

  # Validate the filters argument
  if (!is.list(filters) || is.null(names(filters))) {
    stop(
      "`filters` must be a named list. Example: list(population = 'Gates')",
      call. = FALSE
    )
  }

  # Retrieve the table for metadata schema
  all_tables <- DBI::dbListTables(con)
  if (!"metadata" %in% all_tables) {
    stop(
      "The 'metadata' table does not exist in the local database.",
      call. = FALSE
    )
  }

  full_metadata <- DBI::dbGetQuery(con, "SELECT * FROM metadata")

  if (nrow(full_metadata) == 0) {
    message("The metadata table is empty.")
    return(data.frame())
  }

  # Iteratively filter the metadata based on the provided list of criteria
  filtered_metadata <- full_metadata
  for (col_name in names(filters)) {
    # Skip if column that does not exist
    if (!col_name %in% colnames(filtered_metadata)) {
      warning(
        sprintf(
          "Column '%s' not found in metadata. Skipping this filter.",
          col_name
        ),
        call. = FALSE
      )
      next
    }

    # Subset the metadata to keep only rows matching the current list values
    allowed_values <- filters[[col_name]]
    filtered_metadata <- filtered_metadata[
      filtered_metadata[[col_name]] %in% allowed_values,
      ,
      drop = FALSE
    ]
  }

  # Stop execution if the combined filters eliminated all samples
  if (nrow(filtered_metadata) == 0) {
    message("No samples found matching all combined metadata criteria.")
    return(data.frame())
  }

  # Extract the specific library IDs to keep
  sample_ids_to_keep <- if ("lib" %in% colnames(filtered_metadata)) {
    unique(filtered_metadata$lib)
  } else {
    warning(
      "Metadata is missing the 'lib' column. Cannot identify samples to keep.",
      call. = FALSE
    )
    return(data.frame())
  }

  # Subset the genotype matrix to the filtered samples
  all_matrix_cols <- colnames(genotype_matrix)
  variant_meta_cols <- all_matrix_cols[seq_len(genotype_start_col - 1)]

  available_sample_cols <- intersect(sample_ids_to_keep, all_matrix_cols)

  if (length(available_sample_cols) == 0) {
    message("None of the matching samples were found in the genotype matrix.")
    return(data.frame())
  }

  # Create the sub-population matrix
  sub_population_matrix <- genotype_matrix[,
    c(variant_meta_cols, available_sample_cols),
    drop = FALSE
  ]

  # Recalculate allele metrics on the filtered sub-population
  base_meta_cols <- c(
    "variant_id",
    "chrom",
    "pos",
    "variant_type",
    "ref",
    "alt"
  )

  meta_for_recalc <- intersect(base_meta_cols, variant_meta_cols)

  result <- append_locus_allele_metrics(
    region_matrix = sub_population_matrix,
    meta_data = meta_for_recalc
  )

  return(result)
}



#' Interactive geographic exploration of the samples (local)
#'
#' @param metadata A data frame containing sample metadata tracking information. Must include explicit
#'   numeric \code{"lat"} and \code{"lon"} columns alongside the column specified in \code{color_by}.
#' @param color_by Character. The specific metadata column name used to group and assign discrete
#'   color palette attributes to markers. Defaults to \code{"countryorigin"}.
#'
#' @return A \code{leaflet} map object (htmlwidget) displaying interactive geographic coordinate plots.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Define the path to the curated_sorghum_variant_resource folder
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#'
#' # Establish the connection
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Fetch passport metadata details for all accessions matching the resource
#' sample_metadata <- get_sample_metadata(con = con)
#'
#' # Generate an interactive geographic distribution plot colored by countryorigin
#' query_map_accessions_result <- query_map_accessions(sample_metadata, color_by = "countryorigin")
#' print(query_map_accessions_result)
#'
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#'
#' @export
query_map_accessions <- function(metadata, color_by = "countryorigin") {
  # Check if required external packages (leaflet and tools) exist
  if (!requireNamespace("leaflet", quietly = TRUE)) {
    stop(
      "The 'leaflet' package is required to create interactive maps. ",
      "Please install it by running: install.packages('leaflet')",
      call. = FALSE
    )
  }
  if (!requireNamespace("tools", quietly = TRUE)) {
    stop(
      "The 'tools' package is required. Please run: install.packages('tools')",
      call. = FALSE
    )
  }

  # Check if coordinate columns exist and filter for complete cases
  if (!all(c("lat", "lon") %in% names(metadata))) {
    stop(
      "Metadata must contain 'lat' and 'lon' columns for geographic mapping."
    )
  }

  # Subset to samples with valid geographical coordinates
  plot_data <- metadata[!is.na(metadata$lat) & !is.na(metadata$lon), ]

  if (nrow(plot_data) == 0) {
    stop("No samples with valid latitude and longitude found in the metadata.")
  }

  # Isolate all columns except coordinates to construct interactive HTML popups
  meta_cols <- setdiff(names(plot_data), c("lat", "lon"))

  # HTML popups
  html_components <- lapply(meta_cols, function(col) {
    # Format feature titles via toTitleCase
    clean_title <- tools::toTitleCase(gsub("_", " ", col))
    ifelse(
      is.na(plot_data[[col]]),
      "",
      paste0("<b>", clean_title, ":</b> ", plot_data[[col]], "<br>")
    )
  })

  popup_info <- paste0(
    "<div style='font-family: Arial, sans-serif; font-size: 12px; max-height: 250px; overflow-y: auto;'>",
    do.call(paste0, html_components),
    "</div>"
  )

  # Generate dynamic color palette mapping for Leaflet markers based on the category chosen
  unique_vals <- unique(plot_data[[color_by]])

  pal <- leaflet::colorFactor(
    palette = "viridis",
    domain = unique_vals,
    na.color = "transparent"
  )

  # Construct the Leaflet map
  map <- leaflet::leaflet(data = plot_data) |>
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) |>
    leaflet::addCircleMarkers(
      lng = ~lon,
      lat = ~lat,
      radius = 5,
      color = ~ pal(plot_data[[color_by]]),
      stroke = FALSE,
      fillOpacity = 0.8,
      popup = popup_info,
      label = ~lib
    )

  return(map)
}
