#' Connect to Local Offline Database
#' 
#' Initializes a high-performance, offline DuckDB database engine and maps 
#' local Parquet files to virtual tables for instant querying. This function 
#' creates a persistent connection that should be passed to all downstream 
#' query functions.
#' 
#' @param folder_path Character. The absolute or relative path to the directory 
#'   containing the core Parquet files (`genotypes.parquet`, `variants.parquet`, 
#'   `metadata.parquet`, `annotations.parquet`).
#' @param max_memory Character. Maximum RAM DuckDB is allowed to utilize. 
#'   Defaults to '"8GB"'. Adjust based on system constraints.
#' @param quiet Logical. If \code{TRUE}, suppresses console messages. Defaults to \code{FALSE}.
#' 
#' @return A DBI connection object (`con`) linked to the virtual database.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#' 
#' # Connect to the database at the start of your session
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#' con <- connect_local_db(folder_path = my_db_folder, max_memory = "8GB")
#' 
#' # Pass the connection to downstream functions
#' summary_df <- summarize_sqlite_tables(con)
#' 
#' # Disconnect at the end of your session
#' disconnect_local_db(con)
#' }
#' 
#' @import DBI
#' @export
connect_local_db <- function(folder_path, max_memory = "8GB", quiet = FALSE) {
  
  expected_files <- c("genotypes.parquet", "variants.parquet", 
                      "metadata.parquet", "annotations.parquet")
  
  for (f in expected_files) {
    full_path <- file.path(folder_path, f)
    if (!file.exists(full_path)) {
      stop(paste("Critical file missing:", f, "\nPlease check your folder path:", folder_path))
    }
  }
  
  con <- DBI::dbConnect(duckdb::duckdb())
  
  DBI::dbExecute(con, sprintf("PRAGMA memory_limit='%s'", max_memory))
  
  # Disable DuckDB progress bar to prevent console spam in Shiny
  DBI::dbExecute(con, "SET enable_progress_bar=false")
  
  # 4. Create virtual shortcuts (Views) using safe file paths
  DBI::dbExecute(con, sprintf("CREATE VIEW genotypes AS SELECT * FROM '%s'", file.path(folder_path, "genotypes.parquet")))
  DBI::dbExecute(con, sprintf("CREATE VIEW variants AS SELECT * FROM '%s'", file.path(folder_path, "variants.parquet")))
  DBI::dbExecute(con, sprintf("CREATE VIEW metadata AS SELECT * FROM '%s'", file.path(folder_path, "metadata.parquet")))
  DBI::dbExecute(con, sprintf("CREATE VIEW annotations AS SELECT * FROM '%s'", file.path(folder_path, "annotations.parquet")))
  
  if (!quiet) {
    message("Successfully connected to the local offline database! Virtual views mounted safely.")
  }
  
  return(con)
}




#' Disconnect from the Local Database
#'
#' Safely closes the DuckDB connection and clears the virtual Parquet views from memory.
#' This is the companion function to \code{connect_local_db()} and should be
#' executed at the end of an analytical session to free up system resources.
#'
#' @param con A valid DBI connection object generated by \code{connect_local_db()}.
#' @param quiet Logical. If \code{TRUE}, suppresses console messages. Defaults to \code{FALSE}.
#' @return None. Prints a message confirming the disconnection status.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#' con <- connect_local_db(folder_path = my_db_folder)
#'
#' # Safely close the connection when finished
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
disconnect_local_db <- function(con, quiet = FALSE) {
  # Check if the connection exists and is currently open
  if (!missing(con) && inherits(con, "DBIConnection") && DBI::dbIsValid(con)) {
    DBI::dbDisconnect(con, shutdown = TRUE)
    if (!quiet) {
      message(
        "Successfully disconnected from the local database. Memory cleared."
      )
    }
  } else {
    if (!quiet) {
      message("The database connection is already closed or invalid.")
    }
  }
}




#' List all tables in the database
#' 
#' @param con A DBI connection object to the local database.
#' @return A character vector of table names in the database.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#' con <- connect_local_db(folder_path = my_db_folder)
#' list_sqlite_tables(con)
#' disconnect_local_db(con)
#' }
#'
#' @export
#' @import DBI
list_sqlite_tables <- function(con) {
  # Ensure the connection object is valid
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Retrieve the list of tables from the database connection
  tables <- DBI::dbListTables(con)
  return(tables)
}




#' Get Variant Statistics from the Database
#' 
#' Computes summary statistics for variants across chromosomes, including total counts, 
#' genomic ranges (minimum and maximum positions), and optionally distinct annotated 
#' variant counts.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param include_annotations A logical value indicating whether to include 
#'   statistics for the annotations table. Defaults to \code{TRUE}.
#' 
#' @return A data frame of variant statistics grouped by chromosome.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#'
#' # Get variant statistics across all chromosomes
#' stats_df <- variant_stats(con, include_annotations = TRUE)
#'
#' # Safely close the connection
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
variant_stats <- function(con, include_annotations = TRUE) {
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Extract base statistics from the variants table (counts, min/max pos, unique IDs)
  variant_stats <- DBI::dbGetQuery(
    con,
    "
    SELECT
      chrom,
      COUNT(*) AS n_variants,
      MIN(pos) AS min_pos,
      MAX(pos) AS max_pos,
      COUNT(DISTINCT variant_id) AS n_unique_ids
    FROM variants
    GROUP BY chrom
    ORDER BY chrom
  "
  )

  if (include_annotations) {
    # Query for the count of distinct annotated variants using an inner join
    annotation_counts <- DBI::dbGetQuery(
      con,
      "
      SELECT chrom, COUNT(DISTINCT v.variant_id) AS n_annotated
      FROM variants v
      JOIN annotations a ON v.variant_id = a.variant_id
      GROUP BY chrom
    "
    )
    # Merge the annotation stats with the base stats
    variant_stats <- merge(
      variant_stats,
      annotation_counts,
      by = "chrom",
      all.x = TRUE
    )
    # Fill NA values with 0 for chromosomes lacking annotations
    variant_stats$n_annotated[is.na(variant_stats$n_annotated)] <- 0
  }

  return(variant_stats)
}




#' Summarize Variant Mutation Impacts Per Chromosome
#' 
#' Dynamically cross-tabulates and pivots the counts of functional mutation impact categories 
#' (e.g., HIGH, MODERATE, LOW, MODIFIER) across all chromosomes in the database.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' 
#' @return A wide-format data frame where the first column is \code{chrom}, followed by 
#'   pivoted columns for each impact type (e.g., \code{impact_HIGH}, \code{impact_MODERATE}), 
#'   containing their respective mutation counts.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#'
#' # Generate the wide-format impact profile matrix
#' impact_matrix <- variant_impact_summary(con)
#'
#' # Safely close the connection
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
variant_impact_summary <- function(con) {
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Dynamically pivot the data by counting occurrences of each impact type per chromosome
  query <- "
    PIVOT (
      SELECT v.chrom, a.impact
      FROM annotations a
      JOIN variants v ON a.variant_id = v.variant_id
    )
    ON impact
    USING COUNT(*)
  "

  impact_wide <- DBI::dbGetQuery(con, query)
  # Format column names for clarity (e.g. HIGH -> impact_HIGH)
  col_names <- colnames(impact_wide)
  colnames(impact_wide)[-1] <- paste0("impact_", col_names[-1])

  # Replace any NA with 0 for chromosomes that might be missing a specific impact type entirely
  impact_wide[is.na(impact_wide)] <- 0

  return(impact_wide)
}




#' Name and Row Count for Each Table in the Database
#' 
#' Queries the active local database to instantly retrieve a list of all mounted 
#' tables along with their respective total row counts.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @return A data frame containing two columns: \code{table} (the table name) 
#'   and \code{n_rows} (the total number of rows in that table).
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the local database
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#' con <- connect_local_db(folder_path = my_db_folder)
#' 
#' # Get row counts for all mounted Parquet views
#' database_summary <- summarize_sqlite_tables(con)
#' 
#' # Safely close the connection
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
summarize_sqlite_tables <- function(con) {
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Fetch all available tables
  tables <- DBI::dbListTables(con)

  # Retrieve and store the total number of rows for each table
  counts <- sapply(tables, function(tbl) {
    query <- sprintf("SELECT COUNT(*) FROM %s", tbl)
    DBI::dbGetQuery(con, query)[[1]]
  })

  summary_df <- data.frame(
    table = tables,
    n_rows = counts,
    row.names = NULL
  )

  return(summary_df)
}




#' Get the genomic range of a candidate gene using the Sobic ID from a gff file.
#' @param gene_name A character value indicating the Sobic ID of candidate gene.
#' @param gff_path A character value specifying the path to gff3 file. GZ compressed
#' files and URL file paths are acceptable.
#' @returns A list object of three components indicating the chromosome, start
#' and end coordinates of candidate gene.
#' @examples
#' \donttest{
#' # example code
#'
#' # Path to GFF3 file
#' gff_path <- "https://raw.githubusercontent.com/awkena/panGB/main/Sbicolor_730_v5.1.gene.gff3.gz"
#' gene_coord_gff(gene_name = "Sobic.005G213600",
#'                gff_path = gff_path)
#'
#' }
#' @export
#' @importFrom R.utils isUrl isGzipped gunzip
gene_coord_gff <- function(gene_name,
                           gff_path) {

  # Read GFF and extract gene coordinates
  if (R.utils::isUrl(gff_path)) {

    utils::download.file(gff_path,
                         destfile = file.path(tempdir(), basename(gff_path)))

    # Handle gzipped files by uncompressing before reading
    if (R.utils::isGzipped(file.path(tempdir(), basename(gff_path)))) {

      R.utils::gunzip(file.path(tempdir(), basename(gff_path)),
                      destname = file.path(tempdir(), 'my_gff.gff3'),
                      overwrite = TRUE,
                      remove = TRUE)

      gff <- utils::read.delim(file.path(tempdir(), "my_gff.gff3"),
                               comment.char = "#",
                               header = FALSE,
                               sep = "\t")
    } else {

      gff <- utils::read.delim(file.path(tempdir(), basename(gff_path)),
                               comment.char = "#",
                               header = FALSE,
                               sep = "\t")

    }

    # Ensure tempdir contents are deleted on exit
    on.exit({
      contents <- list.files(tempdir(),
                             full.names = TRUE,
                             recursive = TRUE,
                             all.files = TRUE,
                             include.dirs = TRUE)
      unlink(contents, recursive = TRUE, force = TRUE)
    }, add = TRUE)

  } else if (R.utils::isGzipped(gff_path)) {

    R.utils::gunzip(gff_path,
                    destname = file.path(dirname(gff_path), 'my_gff.gff3'),
                    overwrite = TRUE,
                    remove = TRUE)

    gff <- utils::read.delim(file.path(dirname(gff_path), 'my_gff.gff3'),
                             comment.char = "#",
                             header = FALSE,
                             sep = "\t")
  } else {

    gff <- utils::read.delim(gff_path,
                             comment.char = "#",
                             header = FALSE,
                             sep = "\t")
  }

  # Assign standard column names based on the GFF format specifications
  colnames(gff) <- c("seqid", "source", "type", "start", "end", "score", "strand",
                     "phase", "attributes")
  # Filter to strictly grab gene annotations
  genes <- gff[gff$type == "gene", ]
  # Extract the clean Gene Name from the semicolon-delimited attributes column
  genes$gene_name <- sub(".*Name=([^;]+).*", "\\1", genes$attributes)

  # Find the matching coordinates for the specified candidate gene
  gmatch <- genes[genes$gene_name == gene_name, ]
  if (nrow(gmatch) == 0) stop("Gene not found in GFF.")
  if (nrow(gmatch) > 1) warning("Multiple matches found; using the first match.")

  list(chrom = gmatch$seqid[1],
       start = as.integer(gmatch$start[1]),
       end   = as.integer(gmatch$end[1]))
}





#' List Column Names and Types for a Specified Table
#' 
#' Queries the database schema to return detailed information about column names, 
#' data types, nullability, and key properties for a selected table.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param table_name A character value specifying the name of the table to inspect. 
#'   Must be one of \code{"variants"}, \code{"annotations"}, or \code{"genotypes"}.
#' @return A data frame containing the schema details of the target table, including 
#'   column names and data types.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the local database
#' my_db_folder <- "~/Desktop/curated_sorghum_variant_resource"
#' con <- connect_local_db(folder_path = my_db_folder)
#' 
#' # Inspect the schema layout of the variants table
#' column_schema <- list_table_columns(con, table_name = "variants")
#' 
#' # Safely close the connection
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
list_table_columns <- function(
  con,
  table_name = c("variants", "annotations", "genotypes")
) {
  table_name <- match.arg(table_name)

  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  query <- sprintf("DESCRIBE %s", table_name)
  info <- DBI::dbGetQuery(con, query)

  return(info)
}




#' Query Genomic Data Tables by Coordinate Range
#' 
#' Extracts structural genomic data chunks from a target virtual view based on 
#' chromosome, coordinate windows, and gene identification filters. Automatically 
#' parses and scales underlying list-packed genotype vectors into clear sample columns 
#' when hitting the genotypes engine.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param table_name A character value specifying the target view to query. 
#'   Must be one of \code{"variants"}, \code{"annotations"}, or \code{"genotypes"}.
#' @param chrom A character value specifying the target chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Optional start coordinate for the target window region.
#' @param end Integer. Optional end coordinate for the target window region.
#' @param gene_name A character value indicating the specific Sobic gene model ID. 
#'   Utilized explicitly when subsetting the \code{"annotations"} layout.
#' 
#' @return A data frame containing the targeted genomic records. For the \code{"genotypes"} 
#'   table, it returns individual samples unpacked directly into intuitive wide columns.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Spin up the database pipeline
#' con <- connect_local_db("~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Extract functional functional annotations inside a candidate locus region
#' annota_region <- query_db(con = con, chrom = "Chr05", start = 75104537, 
#'                           end = 75106403, table_name = "annotations", 
#'                           gene_name = "Sobic.005G213600")
#'                           
#' # Extract matrix genotypes within the exact same coordinates window
#' gt_region <- query_db(con = con, chrom = "Chr05", start = 75104537, 
#'                       end = 75106403, table_name = "genotypes")
#'                       
#' # Safely close out resources
#' disconnect_local_db(con)
#' }
#'
#' @import DBI
#' @export
query_db <- function(
  con,
  table_name = c("variants", "annotations", "genotypes"),
  chrom,
  start = NULL,
  end = NULL,
  gene_name = NULL
) {
  table_name <- match.arg(table_name)

  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Check if table exists
  all_tables <- DBI::dbListTables(con)
  if (!(table_name %in% all_tables)) {
    stop(sprintf("Table '%s' does not exist in the database.", table_name))
  }

  # ---  Annotations ---
  if (table_name == "annotations") {
    # Create an inner join across the annotations and variants table to filter by chrom and pos
    sql <- "
      SELECT a.*, v.chrom, v.pos
      FROM annotations a
      JOIN variants v ON a.variant_id = v.variant_id
      WHERE v.chrom = ?"

    params <- list(chrom)

    if (!is.null(start) && !is.null(end)) {
      sql <- paste(sql, "AND v.pos BETWEEN ? AND ?")
      params <- append(params, list(start, end))
    }

    # Filter by gene_name directly in SQL
    if (!is.null(gene_name)) {
      sql <- paste(sql, "AND a.gene_name = ?")
      params <- append(params, list(gene_name))
    }

    sql <- paste(sql, "ORDER BY v.pos")
    result <- DBI::dbGetQuery(con, sql, params = params)

    return(result)
  }

  # --- Genotypes ---
  if (table_name == "genotypes") {
    # Dynamically pull columns to safely support both wide and array-packed 'calls' storage formats
    gt_cols <- DBI::dbListFields(con, "genotypes")
    gt_data_cols <- setdiff(gt_cols, c("variant_id", "chrom", "pos"))
    gt_cols_sql <- paste0("g.", gt_data_cols, collapse = ", ")

    sql <- sprintf(
      "
      SELECT g.variant_id, g.chrom, g.pos, v.variant_type, v.ref, v.alt, %s
      FROM genotypes g
      JOIN variants v ON g.variant_id = v.variant_id
      WHERE g.chrom = ?",
      gt_cols_sql
    )

    params <- list(chrom)

    if (!is.null(start) && !is.null(end)) {
      sql <- paste(sql, "AND g.pos BETWEEN ? AND ?")
      params <- append(params, list(start, end))
    }

    sql <- paste(sql, "ORDER BY g.pos")
    result <- DBI::dbGetQuery(con, sql, params = params)

    if (nrow(result) == 0) {
      return(result)
    }

    # Unpack the array 
    if ("calls" %in% gt_data_cols && length(gt_data_cols) == 1) {

      parsed_list <- result$calls

      sample_names <- NULL

      # Retrieve sample names from metadata
      if ("metadata" %in% all_tables) {
        sample_metadata <- DBI::dbGetQuery(
          con,
          "SELECT lib FROM metadata ORDER BY array_index ASC"
        )

        # Safely extract the first column (assuming it holds the library/sample name)
        if (ncol(sample_metadata) > 0) {
          sample_names <- sample_metadata[[1]]
        }
      }

      if (
        is.null(sample_names) ||
          length(sample_names) != length(parsed_list[[1]])
      ) {
        sample_names <- paste0("Sample_", seq_len(length(parsed_list[[1]])))
      }

      # Reconstruct the matrix to hold all sample calls instantly
      gt_matrix <- do.call(rbind, parsed_list)
      colnames(gt_matrix) <- sample_names

      # Combine the metadata columns with the expanded genotype matrix
      info_cols <- result[, setdiff(names(result), "calls"), drop = FALSE]
      result <- cbind(
        info_cols,
        as.data.frame(gt_matrix, stringsAsFactors = FALSE)
      )
    }
    return(result)
  }

  # --- Variants ---
  # Directly pull and optionally filter variant metadata
  sql <- "
    SELECT * FROM variants v
    WHERE v.chrom = ?"

  params <- list(chrom)

  if (!is.null(start) && !is.null(end)) {
    sql <- paste(sql, "AND v.pos BETWEEN ? AND ?")
    params <- append(params, list(start, end))
  }

  sql <- paste(sql, "ORDER BY v.pos")
  result <- DBI::dbGetQuery(con, sql, params = params)
 
  return(result)
}




#' Extract Variants Based on Functional Mutation Impact
#' 
#' Queries the database to extract variants filtered by their functional impact severity 
#' classification (HIGH, MODERATE, LOW, or MODIFIER) following snpEff conventions. 
#' Optional chromosome and coordinate range windows can be added to narrow down targets.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param impact_level A character vector specifying the variant impact types to retain. 
#'   Allowed classifications are \code{"HIGH"}, \code{"MODERATE"}, \code{"LOW"}, and \code{"MODIFIER"}.
#' @param chrom A character value specifying the chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Optional start coordinate for the genomic region.
#' @param end Integer. Optional end coordinate for the genomic region.
#' 
#' @return A data frame of variants showing their predicted functional impact details 
#'   and positional coordinates.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Extract high-impact variant lines inside a targeted coordinates locus window
#' high_impact_vars <- query_by_impact(con = con,
#'                                     impact_level = "HIGH",
#'                                     chrom = "Chr05",
#'                                     start = 75104537,
#'                                     end = 75106403)
#' 
#' # Safely close out resources
#' disconnect_local_db(con)
#' }
#' 
#' @import DBI
#' @export
query_by_impact <- function(
  con,
  impact_level = c("HIGH", "MODERATE", "LOW", "MODIFIER"),
  chrom = NULL,
  start = NULL,
  end = NULL
) {
  # Validate the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Intersect with allowed options to sanitize the impact levels provided by the user
  allowed <- c("HIGH", "MODERATE", "LOW", "MODIFIER")
  impact_level <- intersect(toupper(impact_level), allowed)

  if (length(impact_level) == 0) {
    stop("No valid impact levels provided.")
  }

  # Dynamically build standard SQL IN placeholders
  placeholders <- paste(rep("?", length(impact_level)), collapse = ", ")

  # Join annotations and variants to retrieve requested variants safely via parameterization
  sql <- sprintf(
    "
    SELECT v.*, a.allele, a.annotation, a.impact, a.gene_name,
           a.gene_id, a.feature_type, a.feature_id, a.transcript_biotype,
           a.rank, a.HGVS_c, a.HGVS_p
    FROM variants v
    JOIN annotations a ON v.variant_id = a.variant_id
    WHERE a.impact IN (%s)",
    placeholders
  )
  params <- as.list(impact_level)

  if (!is.null(chrom)) {
    sql <- paste(sql, "AND v.chrom = ?")
    params <- append(params, list(chrom))

    if (!is.null(start) && !is.null(end)) {
      sql <- paste(sql, "AND v.pos BETWEEN ? AND ?")
      params <- append(params, list(start, end))
    }
  }

  sql <- paste(sql, "ORDER BY v.chrom, v.pos")
  result <- DBI::dbGetQuery(con, sql, params = params)

  return(result)
}




#' Compute Allele Frequencies for a Genotype Matrix
#' 
#' Calculates the reference (REF) and alternate (ALT) allele frequencies for an 
#' extracted wide matrix or data frame of variants by samples. Converts standard VCF 
#' genotype strings (e.g., "0/0", "0|1", "1|1") into numerical alternate allele dosages 
#' (0, 1, 2) to perform population-level frequency calculations.
#' 
#' @param gt A matrix or data frame containing variants (rows) across samples (columns), 
#'   including required variant identification and optional genomic coordinate metadata columns.
#' @param variant_id_col Character. The column name in \code{gt} matching unique variant identifiers. 
#'   Defaults to \code{"variant_id"}.
#' @param chrom_col Character. Optional column name in \code{gt} matching chromosome names. 
#'   Defaults to \code{NULL}.
#' @param pos_col Character. Optional column name in \code{gt} matching genomic positions. 
#'   Defaults to \code{NULL}.
#' 
#' @return A data frame containing unique variant identifiers, optional coordinate tracking columns, 
#'   calculated reference allele frequencies (\code{ref_af}), and alternate allele frequencies (\code{alt_af}).
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Pull wide genotype records for a locus window range
#' gt_region <- query_db(con = con, chrom = "Chr05", start = 75104537, 
#'                       end = 75106403, table_name = "genotypes")
#' 
#' # Compute allele frequencies across all samples in the dataset
#' af_metrics <- calc_af(gt_region, variant_id_col = "variant_id", 
#'                       chrom_col = "chrom", pos_col = "pos")
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @export
calc_af <- function(gt,
                    variant_id_col = 'variant_id',
                    chrom_col = NULL,
                    pos_col = NULL){

  # if(!is.null(chrom)) chrom <- chrom
  # if(!is.null(pos)) pos <- pos

  # Exclude non-genotype mapping/reference columns
  sample_cols <- setdiff(colnames(gt), c(variant_id_col, chrom_col, pos_col))
  gt_matrix <- gt[, sample_cols, drop = FALSE]

  # Function to convert GT string to ALT dosage (0, 1, 2)
  parse_gt <- function(gt) {
    if (is.na(gt)) return(NA)
    if (gt %in% c("0|0", "0/0")) return(0)
    if (gt %in% c("0|1", "1|0", "0/1", "1/0")) return(1)
    if (gt %in% c("1|1", "1/1")) return(2)
    return(NA)  # For unexpected/missing codes
  }

  # Apply conversion function across all sample calls
  dosage_mat <- as.data.frame(apply(gt_matrix, c(1, 2), parse_gt),
                              stringsAsFactors = FALSE)

  # Calculate the alternate allele frequency based on dosages (sum of alt alleles / 2n samples)
  if(nrow(dosage_mat) > 1){
    alt_af <- rowMeans(sapply(dosage_mat, as.numeric), na.rm = TRUE) / 2
  } else{
    # Handle isolated single variant cases cleanly without rowMeans failing
    alt_af <- mean(sapply(dosage_mat, as.numeric), na.rm = TRUE) / 2
  }

  # Format the output data frame with IDs and calculated frequencies
  if(is.null(chrom_col) && is.null(pos_col) ) {

    result <- data.frame(variant_id = gt[, variant_id_col], ref_af = 1 - alt_af,
                         alt_af = alt_af)

  } else {

    result <- data.frame(gt[, c(variant_id_col, chrom_col, pos_col)],
                         ref_af = 1 - alt_af,
                         alt_af = alt_af)

  }

  return(result)

}




#' Filter Extracted Genotypes Based on Alternate Allele Frequency
#' 
#' Passes an extracted genotype matrix through calculation utilities to compute population-level 
#' allele frequencies, then subsets rows down to variants strictly falling between the 
#' specified minimum and maximum alternate allele frequency (MAF) thresholds.
#' 
#' @param gt A matrix or data frame containing variants (rows) across samples (columns), 
#'   including required variant identification and optional genomic coordinate metadata columns.
#' @param variant_id_col Character. The column name in \code{gt} matching unique variant identifiers. 
#'   Defaults to \code{"variant_id"}.
#' @param chrom_col Character. The column name in \code{gt} matching chromosome names. 
#'   Defaults to \code{"chrom"}.
#' @param pos_col Character. The column name in \code{gt} matching genomic positions. 
#'   Defaults to \code{"pos"}.
#' @param min_af Numeric. Minimum alternate allele frequency threshold for filtering. 
#'   Must fall between 0 and 1. Defaults to \code{0}.
#' @param max_af Numeric. Maximum alternate allele frequency threshold for filtering. 
#'   Must fall between 0 and 1. Defaults to \code{1}.
#' 
#' @return A data frame of variants passing the frequency thresholds, tracking their coordinates, 
#'   calculated reference allele frequencies (\code{ref_af}), and alternate allele frequencies (\code{alt_af}).
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Pull wide genotype records for a locus window range
#' gt_region <- query_db(con = con, chrom = "Chr05", start = 75104537, 
#'                       end = 75106403, table_name = "genotypes")
#' 
#' # Filter out rare variants or monomorphic lines by restricting the alternate allele frequency window
#' filtered_vars <- filter_by_af(gt_region, variant_id_col = "variant_id", 
#'                               chrom_col = "chrom", pos_col = "pos", 
#'                               min_af = 0.05, max_af = 0.95)
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @export
filter_by_af <- function(gt,
                         variant_id_col = 'variant_id',
                         chrom_col = 'chrom',
                         pos_col = 'pos',
                         min_af = 0,
                         max_af = 1) {

  if (nrow(gt) == 0) {
    stop("No variant found in the genotype matrix.")
  }

  result <- calc_af(gt,
                    variant_id_col = variant_id_col,
                    chrom_col = chrom_col,
                    pos_col = pos_col)

  # Filter by allele frequency
  result <- result[result$alt_af >= min_af & result$alt_af <= max_af, ]

  return(result)
}





#' Extract Regional Variants Filtered by Allele Frequency
#' 
#' Queries a specific genomic coordinate region to extract genotype matrices, computes 
#' population-level alternate allele frequencies on the fly, and returns a subset of 
#' variants falling strictly within the specified minimum and maximum frequency thresholds.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param min_af Numeric. Minimum alternate allele frequency threshold for filtering. 
#'   Must fall between 0 and 1. Defaults to \code{0}.
#' @param max_af Numeric. Maximum alternate allele frequency threshold for filtering. 
#'   Must fall between 0 and 1. Defaults to \code{1}.
#' @param chrom A character value specifying the target chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Optional start coordinate for the target window region.
#' @param end Integer. Optional end coordinate for the target window region.
#' 
#' @return A data frame of variants passing the frequency thresholds within the defined region, 
#'   tracking their coordinates, calculated reference allele frequencies (\code{ref_af}), 
#'   and alternate allele frequencies (\code{alt_af}).
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Query a specific locus window and filter for common variants (MAF >= 5%)
#' regional_af_vars <- query_by_af(con = con,
#'                                 min_af = 0.05,
#'                                 max_af = 0.95,
#'                                 chrom = "Chr05",
#'                                 start = 75104537,
#'                                 end = 75106403)
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @export
query_by_af <- function(
  con,
  min_af = 0,
  max_af = 1,
  chrom = NULL,
  start = NULL,
  end = NULL
) {
  if (is.null(chrom)) {
    stop("Chromosome must be specified.")
  }

  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # First, query all genotypes in the region
  gt <- query_db(
    con = con,
    table_name = "genotypes",
    chrom = chrom,
    start = start,
    end = end
  )

  if (nrow(gt) == 0) {
    message("No genotype data found for specified region.")
    return(data.frame())
  }

  # Second, calculate the frequencies to allow for subsetting
  result <- calc_af(
    gt,
    variant_id_col = 'variant_id',
    chrom_col = 'chrom',
    pos_col = 'pos'
  )

  # Filter by the minimum and maximum allele frequencies
  result <- result[result$alt_af >= min_af & result$alt_af <= max_af, ]

  return(result)
}





#' Query Genotypes for Specific Variant IDs
#' 
#' Extracts complete genotype call records along with specified variant metadata properties 
#' for an explicit vector list of unique variant identifiers. Automatically resolves 
#' and unpacks internal array-packed list formats seamlessly into standard wide columns.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param variant_ids A character vector of unique variant identifiers to look up (e.g., \code{c("SNP_Chr05_75104557")}).
#' @param variant_id_col A character value specifying the primary key column name for variant IDs. 
#'   Defaults to \code{"variant_id"}.
#' @param variants_table A character value specifying the name of the variants reference table view. 
#'   Defaults to \code{"variants"}.
#' @param genotypes_table A character value specifying the name of the genotype call data table view. 
#'   Defaults to \code{"genotypes"}.
#' @param meta_data A character vector of metadata columns (e.g., \code{"chrom"}, \code{"pos"}, \code{"ref"}) 
#'   to include from the variants table. If \code{NULL}, returns all available schema fields.
#' 
#' @return A data frame containing mapped metadata tracking columns alongside individual sample genotype 
#'   calls formatted in a structured variants-by-samples matrix.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Extract all sample genotypes for an explicit list of target marker strings
#' target_markers <- c("INDEL_Chr05_75104541", "SNP_Chr05_75104557")
#' marker_matrix <- query_genotypes(con = con, 
#'                                  variant_ids = target_markers,
#'                                  meta_data = c("chrom", "pos", "ref", "alt", "variant_type"))
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @import DBI
#' @export
query_genotypes <- function(
  con,
  variant_ids,
  variant_id_col = "variant_id",
  variants_table = 'variants',
  genotypes_table = 'genotypes',
  meta_data = NULL
) {
  # Prevent execution if no variant IDs are provided
  if (length(variant_ids) == 0) {
    warning("The 'variant_ids' vector is empty. No query was executed.")
    return(data.frame())
  }

  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Check if required tables exist in DB
  all_tables <- DBI::dbListTables(con)
  if (!(variants_table %in% all_tables) || !(genotypes_table %in% all_tables)) {
    stop(
      "The specified variants or genotypes table does not exist in the database."
    )
  }

  if (is.null(meta_data)) {
    meta_data <- DBI::dbListFields(con, variants_table)
  } else {
    meta_data <- unique(c(variant_id_col, meta_data))
  }

  # Construct safe comma-separated column names for metadata and genotypes
  meta_cols_sql <- paste0("v.", meta_data, collapse = ", ")

  gt_cols <- DBI::dbListFields(con, genotypes_table)
  gt_data_cols <- setdiff(gt_cols, c(variant_id_col, "chrom", "pos"))
  gt_cols_sql <- paste0("g.", gt_data_cols, collapse = ", ")

  # Dynamically build '?' placeholders for parameterized DB querying
  placeholders <- paste(rep("?", length(variant_ids)), collapse = ", ")
  params <- as.list(variant_ids)

  sql <- sprintf(
    "
    SELECT %s, %s 
    FROM %s v 
    JOIN %s g ON v.%s = g.%s 
    WHERE v.%s IN (%s) 
    ORDER BY v.chrom, v.pos",
    meta_cols_sql,
    gt_cols_sql,
    variants_table,
    genotypes_table,
    variant_id_col,
    variant_id_col,
    variant_id_col,
    placeholders
  )

  res <- DBI::dbGetQuery(con, sql, params = params)

  if (nrow(res) == 0) {
    warning("No data found for the provided variant IDs.")
    return(data.frame())
  }

  if ("pos" %in% colnames(res)) {
    res$pos <- as.integer(res$pos)
  }

  # Parse array-packed genotypes if they are stored structurally within a 'calls' list
  if ("calls" %in% gt_data_cols && length(gt_data_cols) == 1) {
    parsed_list <- res$calls

    sample_names <- NULL
    if ("metadata" %in% all_tables) {
      sample_metadata <- DBI::dbGetQuery(
        con,
        "SELECT lib FROM metadata ORDER BY array_index ASC"
      )
      if (ncol(sample_metadata) > 0) sample_names <- sample_metadata[[1]]
    }

    if (
      is.null(sample_names) || length(sample_names) != length(parsed_list[[1]])
    ) {
      sample_names <- paste0("Sample_", seq_len(length(parsed_list[[1]])))
    }

    gt_matrix <- do.call(rbind, parsed_list)
    colnames(gt_matrix) <- sample_names

    info_cols <- res[, setdiff(names(res), "calls"), drop = FALSE]
    result <- cbind(
      info_cols,
      as.data.frame(gt_matrix, stringsAsFactors = FALSE)
    )
    return(result)
  }

  return(res)
}




#' Count the Distribution of Variant Types in the Database
#' 
#' Queries the database to calculate a global summary of how many variants 
#' exist for each distinct structural classification type (e.g., SNP, INDEL).
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' 
#' @return A data frame containing two columns: \code{variant_type} (the structural 
#'   classification group name) and \code{n} (the total count of variants in that group).
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Get the breakdown counts of SNPs vs INDELs across the resource
#' type_counts <- count_variant_types(con)
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @import DBI
#' @export
count_variant_types <- function(con) {
  table_name <- "variants"

  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  cols <- DBI::dbListFields(con, table_name)
  if (!"variant_type" %in% cols) {
    stop(sprintf(
      "The '%s' table does not have a 'variant_type' column.",
      table_name
    ))
  }

  query <- sprintf(
    "SELECT variant_type, COUNT(*) AS n FROM %s GROUP BY variant_type ORDER BY variant_type",
    table_name
  )

  result <- DBI::dbGetQuery(con, query)

  return(result)
}




#' Summarize Functional Annotations and Impacts for a Genomic Region
#' 
#' Queries a target coordinate window region to generate aggregated cross-tabulations 
#' of snpEff functional annotations (e.g., missense, synonymous) and predicted impact 
#' categories (e.g., HIGH, MODERATE) stratified by variant structural classification type (SNP/INDEL).
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param chrom A character value specifying the target chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Start coordinate for the target window region.
#' @param end Integer. End coordinate for the target window region.
#' @param annotations_table A character value specifying the name of the annotations reference table. 
#'   Defaults to \code{"annotations"}.
#' @param variants_table A character value specifying the name of the variants reference table. 
#'   Defaults to \code{"variants"}.
#' 
#' @return A list object containing three summarized summary data frames:
#' \itemize{
#'   \item \code{annotation_summary}: Counts of distinct functional mutations grouped by type.
#'   \item \code{impact_summary}: Counts of predicted functional impact severities grouped by type.
#'   \item \code{variant_type_totals}: Global marker breakdown counts across the selected coordinate window.
#' }
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Extract functional distribution summaries across a specific gene locus window
#' regional_summaries <- query_ann_summary(con = con,
#'                                         chrom = "Chr05",
#'                                         start = 75104537,
#'                                         end = 75106403)
#' 
#' # Access targeted dataframes directly from the output list
#' print(regional_summaries$impact_summary)
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @export
query_ann_summary <- function(
  con,
  chrom,
  start,
  end,
  annotations_table = "annotations",
  variants_table = "variants"
) {
  # Check if the database connection is valid
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  # Validate required fields exist safely to ensure query compatibility
  ann_fields <- DBI::dbListFields(con, annotations_table)
  var_fields <- DBI::dbListFields(con, variants_table)

  required_ann <- c("variant_id", "annotation", "impact")
  required_var <- c("variant_id", "chrom", "pos", "variant_type")

  if (!all(required_ann %in% ann_fields)) {
    stop(
      "Annotations table must contain: ",
      paste(required_ann, collapse = ", ")
    )
  }
  if (!all(required_var %in% var_fields)) {
    stop("Variants table must contain: ", paste(required_var, collapse = ", "))
  }

  params <- list(chrom, start, end)

  # Aggregate total variants by their types (e.g., SNP vs INDEL) in the given region
  sql_totals <- sprintf(
    "
    SELECT variant_type, COUNT(*) AS total_variants
    FROM %s
    WHERE chrom = ? AND pos BETWEEN ? AND ?
    GROUP BY variant_type",
    variants_table
  )

  variant_type_totals <- DBI::dbGetQuery(con, sql_totals, params = params)

  # Aggregate functional annotations counts categorized by variant type
  sql_ann <- sprintf(
    "
    SELECT a.annotation, v.variant_type, COUNT(*) AS count
    FROM %s a
    JOIN %s v ON a.variant_id = v.variant_id
    WHERE v.chrom = ? AND v.pos BETWEEN ? AND ?
    GROUP BY a.annotation, v.variant_type
    ORDER BY count DESC",
    annotations_table,
    variants_table
  )

  annotation_summary <- DBI::dbGetQuery(con, sql_ann, params = params)

  # Aggregate predicted functional impact counts categorized by variant type
  sql_impact <- sprintf(
    "
    SELECT a.impact, v.variant_type, COUNT(*) AS count
    FROM %s a
    JOIN %s v ON a.variant_id = v.variant_id
    WHERE v.chrom = ? AND v.pos BETWEEN ? AND ?
    GROUP BY a.impact, v.variant_type
    ORDER BY count DESC",
    annotations_table,
    variants_table
  )

  impact_summary <- DBI::dbGetQuery(con, sql_impact, params = params)

  if (nrow(variant_type_totals) == 0) {
    warning("No variants found in the specified region.")
    return(list(
      annotation_summary = data.frame(),
      impact_summary = data.frame(),
      variant_type_totals = data.frame()
    ))
  }

  return(list(
    annotation_summary = annotation_summary,
    impact_summary = impact_summary,
    variant_type_totals = variant_type_totals
  ))
}




#' Retrieve Sample Metadata from the Database
#' 
#' Retrieves accession-level passport data and descriptive population metadata 
#' from the 'metadata' table. It supports safe parameter-driven dynamic column filtering 
#' (e.g., country of origin, race, or cluster) to isolate targeted subpopulations.
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param query_col Character. Optional metadata column name to filter by (e.g., \code{"countryorigin"}). 
#'   If \code{NULL}, all database metadata records are returned.
#' @param query_value Character or Numeric. The explicit attribute value to match within \code{query_col}.
#' 
#' @return A data frame containing the sample metadata records, strictly sorted by their 
#'   \code{array_index} field to ensure perfect structural alignment with downstream genotype matrices.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Fetch metadata for all sorghum accessions originating from Ethiopia
#' eth_samples <- get_sample_metadata(con = con,
#'                                    query_col = "countryorigin",
#'                                    query_value = "Ethiopia")
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @import DBI
#' @export
get_sample_metadata <- function(
  con,
  query_col = NULL,
  query_value = NULL
) {
  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop(
      "Invalid connection. Please run connect_local_db() first and pass the resulting 'con' object."
    )
  }

  if (!("metadata" %in% DBI::dbListTables(con))) {
    stop("Table 'metadata' not found in the database.")
  }

  # Prevent SQL injection by validating query column against database schema
  if (!is.null(query_col)) {
    available_cols <- DBI::dbListFields(con, "metadata")
    if (!query_col %in% available_cols) {
      stop(sprintf("Column '%s' not found in the metadata table.", query_col))
    }
  }

  sql <- "SELECT * FROM metadata"
  params <- list()

  if (!is.null(query_col) && !is.null(query_value)) {
    sql <- paste0(sql, " WHERE ", query_col, " = ?")
    params <- list(query_value) 
  }

  # Enforce sort by array_index to maintain correct alignment mapping with genotypes matrices
  sql <- paste0(sql, " ORDER BY array_index ASC")

  if (length(params) > 0) {
    result <- DBI::dbGetQuery(con, sql, params = params)
  } else {
    result <- DBI::dbGetQuery(con, sql)
  }

  return(result)
}




#' Query Genotypes Filtered by Sample Metadata Attributes
#' 
#' Retrieves genotype calls for a specific genomic region, but restricts the wide-format 
#' column outputs to a subset of samples defined by matching metadata attributes (e.g., 
#' isolating variants only for specific countries of origin, breeding populations, or genetic clusters).
#' 
#' @param con A DBI connection object to the local database generated by \code{connect_local_db()}.
#' @param chrom Character. The target chromosome name (e.g., \code{"Chr05"}).
#' @param start Integer. Optional start coordinate for the target window region.
#' @param end Integer. Optional end coordinate for the target window region.
#' @param meta_col Character. The metadata schema column to filter samples by (e.g., \code{"countryorigin"}).
#' @param meta_value Character or Numeric. The explicit value attribute to match within \code{meta_col} (e.g., \code{"Mali"}).
#' 
#' @return A wide-format data frame (variants x filtered samples) tracking core variant 
#'   properties alongside matching genotype calls.
#' 
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#' 
#' # Get genotypes for a specific gene region, but restrict columns to samples from Mali
#' mali_genotypes <- query_by_metadata(con = con,
#'                                     chrom = "Chr05",
#'                                     start = 75104537,
#'                                     end = 75106403,
#'                                     meta_col = "countryorigin",
#'                                     meta_value = "Mali")
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#' 
#' @export
query_by_metadata <- function(
  con,
  chrom,
  start = NULL,
  end = NULL,
  meta_col,
  meta_value
) {
  
  # Verify the active database connection
  if (missing(con) || !inherits(con, "DBIConnection") || !DBI::dbIsValid(con)) {
    stop("Invalid connection.")
  }
  
  # 1. Retrieve the sample metadata matched via the targeted column and value parameters
  sample_meta <- get_sample_metadata(con, query_col = meta_col, query_value = meta_value)
  
  if (nrow(sample_meta) == 0) {
    message("No samples found matching the metadata criteria.")
    return(data.frame())
  }
  
  # 2. Extract genotype data directly using query_db
  gt_data <- query_db(con, table_name = "genotypes", chrom = chrom, start = start, end = end)
  
  if (nrow(gt_data) == 0) {
    return(gt_data)
  }
  
  # 3. Filter subset the final columns to retain the core variant properties and only the valid samples
  essential_cols <- c("variant_id", "chrom", "pos", "variant_type", "ref", "alt", "qual", "filter")
  keep_cols <- intersect(colnames(gt_data), c(essential_cols, sample_meta$lib, sample_meta$sample))
  
  result <- gt_data[, keep_cols, drop = FALSE]
  return(result)
}


#' Interactive Geographic Exploration of Sorghum Accessions
#'
#' Generates an interactive web map via \code{leaflet} displaying the geographic 
#' distribution of sorghum lines based on latitude and longitude coordinates. Points 
#' are dynamically colored by a user-specified metadata category and display scrollable, 
#' auto-formatted HTML tooltips containing all available metadata attributes.
#'
#' @param metadata A data frame containing sample metadata tracking information. Must include explicit 
#'   numeric \code{"lat"} and \code{"lon"} columns alongside the column specified in \code{color_by}.
#' @param color_by Character. The specific metadata column name used to group and assign discrete 
#'   color palette attributes to markers. Defaults to \code{"countryorigin"}.
#'
#' @return A \code{leaflet} map object (htmlwidget) displaying interactive geographic coordinate plots.
#'
#' @details
#' The function automatically strips out tracking lines containing missing spatial coordinates. 
#' Rather than hardcoding fixed tooltip categories, it dynamically extracts all non-coordinate metadata 
#' attributes present in the provided matrix, formatting them into clear, scrollable HTML popup panels 
#' for every marker.
#'
#' \strong{Dependency Note:} To keep core package requirements lean, \code{leaflet} 
#' and \code{tools} are configured as suggested package attachments. If they are absent from the local 
#' execution workspace, the script will halt cleanly and prompt appropriate installation commands.
#'
#' @examples
#' \dontrun{
#' # Load the package
#' library(panGenomeBreedr)
#'
#' # Connect to the database pipeline
#' con <- connect_local_db(folder_path = "~/Desktop/curated_sorghum_variant_resource")
#'
#' # Fetch passport metadata details for all accessions matching the resource
#' sample_metadata <- get_sample_metadata(con = con)
#'
#' # Generate an interactive geographic distribution plot colored by K-Means genetic cluster assignments
#' query_map_accessions(sample_metadata, color_by = "kmeans_cluster")
#' 
#' # Safely close out the database connection
#' disconnect_local_db(con)
#' }
#'
#' @export
query_map_accessions <- function(metadata, color_by = "countryorigin") {
  # Check if required external packages (leaflet and tools) exist 
  if (!requireNamespace("leaflet", quietly = TRUE)) {
    stop(
      "The 'leaflet' package is required to create interactive maps. ",
      "Please install it by running: install.packages('leaflet')",
      call. = FALSE
    )
  }
  if (!requireNamespace("tools", quietly = TRUE)) {
    stop(
      "The 'tools' package is required. Please run: install.packages('tools')",
      call. = FALSE
    )
  }

  # Check if coordinate columns exist and filter for complete cases
  if (!all(c("lat", "lon") %in% names(metadata))) {
    stop(
      "Metadata must contain 'lat' and 'lon' columns for geographic mapping."
    )
  }

  # Subset to samples with valid geographical coordinates
  plot_data <- metadata[!is.na(metadata$lat) & !is.na(metadata$lon), ]

  if (nrow(plot_data) == 0) {
    stop("No samples with valid latitude and longitude found in the metadata.")
  }

  # Isolate all columns except coordinates to construct interactive HTML popups
  meta_cols <- setdiff(names(plot_data), c("lat", "lon"))

  # HTML popups
  html_components <- lapply(meta_cols, function(col) {
    # Format feature titles via toTitleCase
    clean_title <- tools::toTitleCase(gsub("_", " ", col))
    ifelse(
      is.na(plot_data[[col]]),
      "",
      paste0("<b>", clean_title, ":</b> ", plot_data[[col]], "<br>")
    )
  })

  popup_info <- paste0(
    "<div style='font-family: Arial, sans-serif; font-size: 12px; max-height: 250px; overflow-y: auto;'>",
    do.call(paste0, html_components),
    "</div>"
  )

  # Generate dynamic color palette mapping for Leaflet markers based on the category chosen
  unique_vals <- unique(plot_data[[color_by]])

  pal <- leaflet::colorFactor(
    palette = "viridis",
    domain = unique_vals,
    na.color = "transparent"
  )

  # Construct the Leaflet map
  map <- leaflet::leaflet(data = plot_data) |>
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) |>
    leaflet::addCircleMarkers(
      lng = ~lon,
      lat = ~lat,
      radius = 5,
      color = ~ pal(plot_data[[color_by]]),
      stroke = FALSE,
      fillOpacity = 0.8,
      popup = popup_info,
      label = ~lib
    )

  return(map)
}






# #' Generic Trait Association Audit (Local SQLite Version)
# #'
# #' This function performs an association analysis between a specific genomic variant
# #' and a phenotypic trait. It pulls genotypes directly from the local SQLite database,
# #' merges them with provided phenotypic data, and generates a statistical summary plot
# #' using Kruskal-Wallis (quantitative) or Chi-Square (qualitative) tests.
# #'
# #' @param db_path A character string specifying the file path to the SQLite database.
# #' @param variant_id Character. The specific SNP or INDEL ID to analyze (e.g., "SNP_Chr05_75104557").
# #' @param pheno_df Data frame containing phenotypic data. The first column must contain accession identifiers (e.g., PI numbers).
# #' @param trait_col Character. The name of the column in \code{pheno_df} containing trait scores.
# #' @param trait_type Character. Either "qualitative" or "quantitative". Determines the statistical test and plot type.
# #'
# #' @returns A \code{ggplot2} object displaying the association boxplot/bar chart and a statistical summary.
# #'
# #' @examples
# #' \donttest{
# #' library(panGenomeBreedr)
# #'
# #' # Define tempdir and setup mini SQLite database
# #' path <- tempdir()
# #' mini_db <- system.file("extdata", "mini_sorghum_variant_vcf.db.gz", package = "panGenomeBreedr", mustWork = TRUE)
# #' mini_db_path <- file.path(path, 'mini_sorghum_variant_vcf.db')
# #' R.utils::gunzip(mini_db, destname = mini_db_path, remove = FALSE)
# #'
# #' # 1. Fetch valid sample IDs to create dummy phenotype data
# #' valid_samples <- get_sample_metadata(mini_db_path)$pinumber
# #'
# #' # 2. Create a dummy quantitative phenotype dataframe
# #' set.seed(123)
# #' dummy_pheno <- data.frame(
# #'   pinumber = valid_samples,
# #'   plant_height = rnorm(length(valid_samples), mean = 150, sd = 20)
# #' )
# #'
# #' # 3. Run the association audit
# #' plot_trait_association(
# #'   db_path = mini_db_path,
# #'   variant_id = "SNP_Chr05_75104557",
# #'   pheno_df = dummy_pheno,
# #'   trait_col = "plant_height",
# #'   trait_type = "quantitative"
# #' )
# #'
# #' # Clean tempdir
# #' unlink(list.files(tempdir(), full.names = TRUE, recursive = TRUE, include.dirs = TRUE), recursive = TRUE, force = TRUE)
# #' }
# #'
# #' @export
# #' @import ggplot2
# #' @import stats
# #' @import DBI
# #' @importFrom RSQLite SQLite
# plot_trait_association <- function(
#   db_path,
#   variant_id,
#   pheno_df,
#   trait_col,
#   trait_type = c("qualitative", "quantitative")
# ) {
#   trait_type <- match.arg(trait_type)
#   genotype <- NULL

#   if (
#     trait_type == "qualitative" && !requireNamespace("scales", quietly = TRUE)
#   ) {
#     stop("The 'scales' package is required. Please install it.")
#   }

#   # 1. Pull genotype data directly from SQLite
#   gt_data <- query_genotypes(db_path = db_path, variant_ids = variant_id)

#   if (nrow(gt_data) == 0) {
#     stop(paste("Variant ID", variant_id, "was not found."))
#   }

#   # 2. Fetch functional annotations for the verdict logic
#   con <- DBI::dbConnect(RSQLite::SQLite(), db_path)
#   ann_info <- DBI::dbGetQuery(
#     con,
#     "SELECT annotation, impact FROM annotations WHERE variant_id = :id",
#     params = list(id = variant_id)
#   )
#   DBI::dbDisconnect(con)

#   # 3. Fetch sample metadata mapping
#   pi_map <- get_sample_metadata(db_path)

#   # Align genotype samples with phenotype PI numbers
#   sample_cols <- setdiff(
#     names(gt_data),
#     c(
#       "variant_id",
#       "chrom",
#       "pos",
#       "ref",
#       "alt",
#       "qual",
#       "filter",
#       "variant_type"
#     )
#   )

#   gt_long <- data.frame(
#     pinumber = pi_map$pinumber[match(sample_cols, pi_map$lib)],
#     genotype = as.character(unlist(gt_data[1, sample_cols])),
#     stringsAsFactors = FALSE
#   )

#   colnames(pheno_df)[1] <- "pinumber"
#   plot_data <- merge(gt_long, pheno_df, by = "pinumber")

#   plot_data <- plot_data[
#     !is.na(plot_data[[trait_col]]) &
#       plot_data[[trait_col]] != "-" &
#       plot_data$genotype != "./.",
#   ]

#   if (trait_type == "quantitative") {
#     if (!is.numeric(plot_data[[trait_col]])) {
#       plot_data[[trait_col]] <- as.numeric(gsub(
#         ".*[^0-9.]",
#         "",
#         as.character(plot_data[[trait_col]])
#       ))
#     }
#   } else {
#     plot_data[[trait_col]] <- as.factor(plot_data[[trait_col]])
#   }

#   alleles <- unlist(strsplit(plot_data$genotype, "[|/]"))
#   maf <- min(table(alleles)) / length(alleles)
#   p_val <- NA
#   pve_val <- 0

#   if (trait_type == "quantitative") {
#     p_val <- stats::kruskal.test(
#       plot_data[[trait_col]] ~ plot_data$genotype
#     )$p.value
#     pve_val <- summary(stats::lm(
#       plot_data[[trait_col]] ~ plot_data$genotype
#     ))$r.squared
#   } else {
#     p_val <- stats::chisq.test(
#       table(plot_data$genotype, plot_data[[trait_col]]),
#       simulate.p.value = TRUE
#     )$p.value
#   }

#   impact <- if (nrow(ann_info) > 0) ann_info$impact[1] else "UNKNOWN"
#   is_sig <- !is.na(p_val) && p_val < 0.05

#   verdict <- if (is_sig && (pve_val > 0.1 || impact == "HIGH")) {
#     "VALIDATE"
#   } else if (is_sig) {
#     "CAUTION"
#   } else {
#     "DISCARD"
#   }

#   p <- ggplot2::ggplot(plot_data, ggplot2::aes(x = genotype)) +
#     ggplot2::theme_minimal() +
#     ggplot2::scale_fill_brewer(palette = "Set1")

#   if (trait_type == "quantitative") {
#     p <- p +
#       ggplot2::aes(y = .data[[trait_col]], fill = genotype) +
#       ggplot2::geom_boxplot(outlier.shape = NA, alpha = 0.5) +
#       ggplot2::geom_jitter(width = 0.2, alpha = 0.4)
#   } else {
#     p <- p +
#       ggplot2::aes(fill = .data[[trait_col]]) +
#       ggplot2::geom_bar(position = "fill", color = "white", linewidth = 0.3) +
#       ggplot2::scale_y_continuous(labels = scales::percent)
#   }

#   p <- p +
#     ggplot2::labs(
#       title = paste("Association Audit:", variant_id),
#       subtitle = paste0(
#         "P-val: ",
#         format.pval(p_val, digits = 3),
#         " | PVE: ",
#         round(pve_val * 100, 1),
#         "% | MAF: ",
#         round(maf, 3),
#         "\nImpact: ",
#         impact,
#         " | Verdict: ",
#         verdict
#       ),
#       x = "Genotype",
#       y = if (trait_type == "quantitative") trait_col else "Frequency (%)"
#     )

#   return(p)
# }